-- =========================================================================
-- UNE Sports — Catálogo completo región / provincia / distrito del Perú
-- Fuente: https://github.com/RitchieRD/ubigeos-peru-data (25 regiones,
-- separando Callao de Lima; nombres normalizados a Capitalización estándar).
-- Seguro de ejecutar sobre una base ya en producción: solo reemplaza el
-- contenido de distritos_peru, no toca negocios/blog/reseñas/mensajes.
-- =========================================================================

SET NAMES utf8mb4;
DELETE FROM distritos_peru;
ALTER TABLE distritos_peru AUTO_INCREMENT = 1;

INSERT INTO distritos_peru (region, provincia, distrito) VALUES
  ('Amazonas', 'Bagua', 'Aramango'),
  ('Amazonas', 'Bagua', 'Bagua'),
  ('Amazonas', 'Bagua', 'Copallin'),
  ('Amazonas', 'Bagua', 'El Parco'),
  ('Amazonas', 'Bagua', 'Imaza'),
  ('Amazonas', 'Bagua', 'La Peca'),
  ('Amazonas', 'Bongara', 'Chisquilla'),
  ('Amazonas', 'Bongara', 'Churuja'),
  ('Amazonas', 'Bongara', 'Corosha'),
  ('Amazonas', 'Bongara', 'Cuispes'),
  ('Amazonas', 'Bongara', 'Florida'),
  ('Amazonas', 'Bongara', 'Jazan'),
  ('Amazonas', 'Bongara', 'Jumbilla'),
  ('Amazonas', 'Bongara', 'Recta'),
  ('Amazonas', 'Bongara', 'San Carlos'),
  ('Amazonas', 'Bongara', 'Shipasbamba'),
  ('Amazonas', 'Bongara', 'Valera'),
  ('Amazonas', 'Bongara', 'Yambrasbamba'),
  ('Amazonas', 'Chachapoyas', 'Asuncion'),
  ('Amazonas', 'Chachapoyas', 'Balsas'),
  ('Amazonas', 'Chachapoyas', 'Chachapoyas'),
  ('Amazonas', 'Chachapoyas', 'Cheto'),
  ('Amazonas', 'Chachapoyas', 'Chiliquin'),
  ('Amazonas', 'Chachapoyas', 'Chuquibamba'),
  ('Amazonas', 'Chachapoyas', 'Granada'),
  ('Amazonas', 'Chachapoyas', 'Huancas'),
  ('Amazonas', 'Chachapoyas', 'La Jalca'),
  ('Amazonas', 'Chachapoyas', 'Leimebamba'),
  ('Amazonas', 'Chachapoyas', 'Levanto'),
  ('Amazonas', 'Chachapoyas', 'Magdalena'),
  ('Amazonas', 'Chachapoyas', 'Mariscal Castilla'),
  ('Amazonas', 'Chachapoyas', 'Molinopampa'),
  ('Amazonas', 'Chachapoyas', 'Montevideo'),
  ('Amazonas', 'Chachapoyas', 'Olleros'),
  ('Amazonas', 'Chachapoyas', 'Quinjalca'),
  ('Amazonas', 'Chachapoyas', 'San Francisco de Daguas'),
  ('Amazonas', 'Chachapoyas', 'San Isidro de Maino'),
  ('Amazonas', 'Chachapoyas', 'Soloco'),
  ('Amazonas', 'Chachapoyas', 'Sonche'),
  ('Amazonas', 'Condorcanqui', 'El Cenepa'),
  ('Amazonas', 'Condorcanqui', 'Nieva'),
  ('Amazonas', 'Condorcanqui', 'Rio Santiago'),
  ('Amazonas', 'Luya', 'Camporredondo'),
  ('Amazonas', 'Luya', 'Cocabamba'),
  ('Amazonas', 'Luya', 'Colcamar'),
  ('Amazonas', 'Luya', 'Conila'),
  ('Amazonas', 'Luya', 'Inguilpata'),
  ('Amazonas', 'Luya', 'Lamud'),
  ('Amazonas', 'Luya', 'Longuita'),
  ('Amazonas', 'Luya', 'Lonya Chico'),
  ('Amazonas', 'Luya', 'Luya'),
  ('Amazonas', 'Luya', 'Luya Viejo'),
  ('Amazonas', 'Luya', 'Maria'),
  ('Amazonas', 'Luya', 'Ocalli'),
  ('Amazonas', 'Luya', 'Ocumal'),
  ('Amazonas', 'Luya', 'Pisuquia'),
  ('Amazonas', 'Luya', 'Providencia'),
  ('Amazonas', 'Luya', 'San Cristobal'),
  ('Amazonas', 'Luya', 'San Francisco del Yeso'),
  ('Amazonas', 'Luya', 'San Jeronimo'),
  ('Amazonas', 'Luya', 'San Juan de Lopecancha'),
  ('Amazonas', 'Luya', 'Santa Catalina'),
  ('Amazonas', 'Luya', 'Santo Tomas'),
  ('Amazonas', 'Luya', 'Tingo'),
  ('Amazonas', 'Luya', 'Trita'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Chirimoto'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Cochamal'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Huambo'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Limabamba'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Longar'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Mariscal Benavides'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Milpuc'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Omia'),
  ('Amazonas', 'Rodriguez de Mendoza', 'San Nicolas'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Santa Rosa'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Totora'),
  ('Amazonas', 'Rodriguez de Mendoza', 'Vista Alegre'),
  ('Amazonas', 'Utcubamba', 'Bagua Grande'),
  ('Amazonas', 'Utcubamba', 'Cajaruro'),
  ('Amazonas', 'Utcubamba', 'Cumba'),
  ('Amazonas', 'Utcubamba', 'El Milagro'),
  ('Amazonas', 'Utcubamba', 'Jamalca'),
  ('Amazonas', 'Utcubamba', 'Lonya Grande'),
  ('Amazonas', 'Utcubamba', 'Yamon'),
  ('Apurímac', 'Abancay', 'Abancay'),
  ('Apurímac', 'Abancay', 'Chacoche'),
  ('Apurímac', 'Abancay', 'Circa'),
  ('Apurímac', 'Abancay', 'Curahuasi'),
  ('Apurímac', 'Abancay', 'Huanipaca'),
  ('Apurímac', 'Abancay', 'Lambrama'),
  ('Apurímac', 'Abancay', 'Pichirhua'),
  ('Apurímac', 'Abancay', 'San Pedro de Cachora'),
  ('Apurímac', 'Abancay', 'Tamburco'),
  ('Apurímac', 'Andahuaylas', 'Andahuaylas'),
  ('Apurímac', 'Andahuaylas', 'Andarapa'),
  ('Apurímac', 'Andahuaylas', 'Chiara'),
  ('Apurímac', 'Andahuaylas', 'Huancarama'),
  ('Apurímac', 'Andahuaylas', 'Huancaray'),
  ('Apurímac', 'Andahuaylas', 'Huayana'),
  ('Apurímac', 'Andahuaylas', 'Jose Maria Arguedas'),
  ('Apurímac', 'Andahuaylas', 'Kaquiabamba'),
  ('Apurímac', 'Andahuaylas', 'Kishuara'),
  ('Apurímac', 'Andahuaylas', 'Pacobamba'),
  ('Apurímac', 'Andahuaylas', 'Pacucha'),
  ('Apurímac', 'Andahuaylas', 'Pampachiri'),
  ('Apurímac', 'Andahuaylas', 'Pomacocha'),
  ('Apurímac', 'Andahuaylas', 'San Antonio de Cachi'),
  ('Apurímac', 'Andahuaylas', 'San Jeronimo'),
  ('Apurímac', 'Andahuaylas', 'San Miguel de Chaccrampa'),
  ('Apurímac', 'Andahuaylas', 'Santa Maria de Chicmo'),
  ('Apurímac', 'Andahuaylas', 'Talavera'),
  ('Apurímac', 'Andahuaylas', 'Tumay Huaraca'),
  ('Apurímac', 'Andahuaylas', 'Turpo'),
  ('Apurímac', 'Antabamba', 'Antabamba'),
  ('Apurímac', 'Antabamba', 'El Oro'),
  ('Apurímac', 'Antabamba', 'Huaquirca'),
  ('Apurímac', 'Antabamba', 'Juan Espinoza Medrano'),
  ('Apurímac', 'Antabamba', 'Oropesa'),
  ('Apurímac', 'Antabamba', 'Pachaconas'),
  ('Apurímac', 'Antabamba', 'Sabaino'),
  ('Apurímac', 'Aymaraes', 'Capaya'),
  ('Apurímac', 'Aymaraes', 'Caraybamba'),
  ('Apurímac', 'Aymaraes', 'Chalhuanca'),
  ('Apurímac', 'Aymaraes', 'Chapimarca'),
  ('Apurímac', 'Aymaraes', 'Colcabamba'),
  ('Apurímac', 'Aymaraes', 'Cotaruse'),
  ('Apurímac', 'Aymaraes', 'Huayllo'),
  ('Apurímac', 'Aymaraes', 'Justo Apu Sahuaraura'),
  ('Apurímac', 'Aymaraes', 'Lucre'),
  ('Apurímac', 'Aymaraes', 'Pocohuanca'),
  ('Apurímac', 'Aymaraes', 'San Juan de Chacña'),
  ('Apurímac', 'Aymaraes', 'Sañayca'),
  ('Apurímac', 'Aymaraes', 'Soraya'),
  ('Apurímac', 'Aymaraes', 'Tapairihua'),
  ('Apurímac', 'Aymaraes', 'Tintay'),
  ('Apurímac', 'Aymaraes', 'Toraya'),
  ('Apurímac', 'Aymaraes', 'Yanaca'),
  ('Apurímac', 'Chincheros', 'Ahuayro'),
  ('Apurímac', 'Chincheros', 'Anco-huallo'),
  ('Apurímac', 'Chincheros', 'Chincheros'),
  ('Apurímac', 'Chincheros', 'Cocharcas'),
  ('Apurímac', 'Chincheros', 'El Porvenir'),
  ('Apurímac', 'Chincheros', 'Huaccana'),
  ('Apurímac', 'Chincheros', 'Los Chankas'),
  ('Apurímac', 'Chincheros', 'Ocobamba'),
  ('Apurímac', 'Chincheros', 'Ongoy'),
  ('Apurímac', 'Chincheros', 'Ranracancha'),
  ('Apurímac', 'Chincheros', 'Rocchacc'),
  ('Apurímac', 'Chincheros', 'Uranmarca'),
  ('Apurímac', 'Cotabambas', 'Challhuahuacho'),
  ('Apurímac', 'Cotabambas', 'Cotabambas'),
  ('Apurímac', 'Cotabambas', 'Coyllurqui'),
  ('Apurímac', 'Cotabambas', 'Haquira'),
  ('Apurímac', 'Cotabambas', 'Mara'),
  ('Apurímac', 'Cotabambas', 'Tambobamba'),
  ('Apurímac', 'Grau', 'Chuquibambilla'),
  ('Apurímac', 'Grau', 'Curasco'),
  ('Apurímac', 'Grau', 'Curpahuasi'),
  ('Apurímac', 'Grau', 'Gamarra'),
  ('Apurímac', 'Grau', 'Huayllati'),
  ('Apurímac', 'Grau', 'Mamara'),
  ('Apurímac', 'Grau', 'Micaela Bastidas'),
  ('Apurímac', 'Grau', 'Pataypampa'),
  ('Apurímac', 'Grau', 'Progreso'),
  ('Apurímac', 'Grau', 'San Antonio'),
  ('Apurímac', 'Grau', 'Santa Rosa'),
  ('Apurímac', 'Grau', 'Turpay'),
  ('Apurímac', 'Grau', 'Vilcabamba'),
  ('Apurímac', 'Grau', 'Virundo'),
  ('Arequipa', 'Arequipa', 'Alto Selva Alegre'),
  ('Arequipa', 'Arequipa', 'Arequipa'),
  ('Arequipa', 'Arequipa', 'Cayma'),
  ('Arequipa', 'Arequipa', 'Cerro Colorado'),
  ('Arequipa', 'Arequipa', 'Characato'),
  ('Arequipa', 'Arequipa', 'Chiguata'),
  ('Arequipa', 'Arequipa', 'Jacobo Hunter'),
  ('Arequipa', 'Arequipa', 'Jose Luis Bustamante y Rivero'),
  ('Arequipa', 'Arequipa', 'La Joya'),
  ('Arequipa', 'Arequipa', 'Mariano Melgar'),
  ('Arequipa', 'Arequipa', 'Miraflores'),
  ('Arequipa', 'Arequipa', 'Mollebaya'),
  ('Arequipa', 'Arequipa', 'Paucarpata'),
  ('Arequipa', 'Arequipa', 'Pocsi'),
  ('Arequipa', 'Arequipa', 'Polobaya'),
  ('Arequipa', 'Arequipa', 'Quequeña'),
  ('Arequipa', 'Arequipa', 'Sabandia'),
  ('Arequipa', 'Arequipa', 'Sachaca'),
  ('Arequipa', 'Arequipa', 'San Juan de Siguas'),
  ('Arequipa', 'Arequipa', 'San Juan de Tarucani'),
  ('Arequipa', 'Arequipa', 'Santa Isabel de Siguas'),
  ('Arequipa', 'Arequipa', 'Santa Rita de Siguas'),
  ('Arequipa', 'Arequipa', 'Socabaya'),
  ('Arequipa', 'Arequipa', 'Tiabaya'),
  ('Arequipa', 'Arequipa', 'Uchumayo'),
  ('Arequipa', 'Arequipa', 'Vitor'),
  ('Arequipa', 'Arequipa', 'Yanahuara'),
  ('Arequipa', 'Arequipa', 'Yarabamba'),
  ('Arequipa', 'Arequipa', 'Yura'),
  ('Arequipa', 'Camana', 'Camana'),
  ('Arequipa', 'Camana', 'Jose Maria Quimper'),
  ('Arequipa', 'Camana', 'Mariano Nicolas Valcarcel'),
  ('Arequipa', 'Camana', 'Mariscal Caceres'),
  ('Arequipa', 'Camana', 'Nicolas de Pierola'),
  ('Arequipa', 'Camana', 'Ocoña'),
  ('Arequipa', 'Camana', 'Quilca'),
  ('Arequipa', 'Camana', 'Samuel Pastor'),
  ('Arequipa', 'Caraveli', 'Acari'),
  ('Arequipa', 'Caraveli', 'Atico'),
  ('Arequipa', 'Caraveli', 'Atiquipa'),
  ('Arequipa', 'Caraveli', 'Bella Union'),
  ('Arequipa', 'Caraveli', 'Cahuacho'),
  ('Arequipa', 'Caraveli', 'Caraveli'),
  ('Arequipa', 'Caraveli', 'Chala'),
  ('Arequipa', 'Caraveli', 'Chaparra'),
  ('Arequipa', 'Caraveli', 'Huanuhuanu'),
  ('Arequipa', 'Caraveli', 'Jaqui'),
  ('Arequipa', 'Caraveli', 'Lomas'),
  ('Arequipa', 'Caraveli', 'Quicacha'),
  ('Arequipa', 'Caraveli', 'Yauca'),
  ('Arequipa', 'Castilla', 'Andagua'),
  ('Arequipa', 'Castilla', 'Aplao'),
  ('Arequipa', 'Castilla', 'Ayo'),
  ('Arequipa', 'Castilla', 'Chachas'),
  ('Arequipa', 'Castilla', 'Chilcaymarca'),
  ('Arequipa', 'Castilla', 'Choco'),
  ('Arequipa', 'Castilla', 'Huancarqui'),
  ('Arequipa', 'Castilla', 'Machaguay'),
  ('Arequipa', 'Castilla', 'Orcopampa'),
  ('Arequipa', 'Castilla', 'Pampacolca'),
  ('Arequipa', 'Castilla', 'Tipan'),
  ('Arequipa', 'Castilla', 'Uraca'),
  ('Arequipa', 'Castilla', 'Uñon'),
  ('Arequipa', 'Castilla', 'Viraco'),
  ('Arequipa', 'Caylloma', 'Achoma'),
  ('Arequipa', 'Caylloma', 'Cabanaconde'),
  ('Arequipa', 'Caylloma', 'Callalli'),
  ('Arequipa', 'Caylloma', 'Caylloma'),
  ('Arequipa', 'Caylloma', 'Chivay'),
  ('Arequipa', 'Caylloma', 'Coporaque'),
  ('Arequipa', 'Caylloma', 'Huambo'),
  ('Arequipa', 'Caylloma', 'Huanca'),
  ('Arequipa', 'Caylloma', 'Ichupampa'),
  ('Arequipa', 'Caylloma', 'Lari'),
  ('Arequipa', 'Caylloma', 'Lluta'),
  ('Arequipa', 'Caylloma', 'Maca'),
  ('Arequipa', 'Caylloma', 'Madrigal'),
  ('Arequipa', 'Caylloma', 'Majes'),
  ('Arequipa', 'Caylloma', 'San Antonio de Chuca'),
  ('Arequipa', 'Caylloma', 'Sibayo'),
  ('Arequipa', 'Caylloma', 'Tapay'),
  ('Arequipa', 'Caylloma', 'Tisco'),
  ('Arequipa', 'Caylloma', 'Tuti'),
  ('Arequipa', 'Caylloma', 'Yanque'),
  ('Arequipa', 'Condesuyos', 'Andaray'),
  ('Arequipa', 'Condesuyos', 'Cayarani'),
  ('Arequipa', 'Condesuyos', 'Chichas'),
  ('Arequipa', 'Condesuyos', 'Chuquibamba'),
  ('Arequipa', 'Condesuyos', 'Iray'),
  ('Arequipa', 'Condesuyos', 'Rio Grande'),
  ('Arequipa', 'Condesuyos', 'Salamanca'),
  ('Arequipa', 'Condesuyos', 'Yanaquihua'),
  ('Arequipa', 'Islay', 'Cocachacra'),
  ('Arequipa', 'Islay', 'Dean Valdivia'),
  ('Arequipa', 'Islay', 'Islay'),
  ('Arequipa', 'Islay', 'Mejia'),
  ('Arequipa', 'Islay', 'Mollendo'),
  ('Arequipa', 'Islay', 'Punta de Bombon'),
  ('Arequipa', 'La Union', 'Alca'),
  ('Arequipa', 'La Union', 'Charcana'),
  ('Arequipa', 'La Union', 'Cotahuasi'),
  ('Arequipa', 'La Union', 'Huaynacotas'),
  ('Arequipa', 'La Union', 'Pampamarca'),
  ('Arequipa', 'La Union', 'Puyca'),
  ('Arequipa', 'La Union', 'Quechualla'),
  ('Arequipa', 'La Union', 'Sayla'),
  ('Arequipa', 'La Union', 'Tauria'),
  ('Arequipa', 'La Union', 'Tomepampa'),
  ('Arequipa', 'La Union', 'Toro'),
  ('Ayacucho', 'Cangallo', 'Cangallo'),
  ('Ayacucho', 'Cangallo', 'Chuschi'),
  ('Ayacucho', 'Cangallo', 'Los Morochucos'),
  ('Ayacucho', 'Cangallo', 'Maria Parado de Bellido'),
  ('Ayacucho', 'Cangallo', 'Paras'),
  ('Ayacucho', 'Cangallo', 'Totos'),
  ('Ayacucho', 'Huamanga', 'Acocro'),
  ('Ayacucho', 'Huamanga', 'Acos Vinchos'),
  ('Ayacucho', 'Huamanga', 'Andres Avelino Caceres Dorregaray'),
  ('Ayacucho', 'Huamanga', 'Ayacucho'),
  ('Ayacucho', 'Huamanga', 'Carmen Alto'),
  ('Ayacucho', 'Huamanga', 'Chiara'),
  ('Ayacucho', 'Huamanga', 'Jesus Nazareno'),
  ('Ayacucho', 'Huamanga', 'Ocros'),
  ('Ayacucho', 'Huamanga', 'Pacaycasa'),
  ('Ayacucho', 'Huamanga', 'Quinua'),
  ('Ayacucho', 'Huamanga', 'San Jose de Ticllas'),
  ('Ayacucho', 'Huamanga', 'San Juan Bautista'),
  ('Ayacucho', 'Huamanga', 'Santiago de Pischa'),
  ('Ayacucho', 'Huamanga', 'Socos'),
  ('Ayacucho', 'Huamanga', 'Tambillo'),
  ('Ayacucho', 'Huamanga', 'Vinchos'),
  ('Ayacucho', 'Huanca Sancos', 'Carapo'),
  ('Ayacucho', 'Huanca Sancos', 'Sacsamarca'),
  ('Ayacucho', 'Huanca Sancos', 'Sancos'),
  ('Ayacucho', 'Huanca Sancos', 'Santiago de Lucanamarca'),
  ('Ayacucho', 'Huanta', 'Ayahuanco'),
  ('Ayacucho', 'Huanta', 'Canayre'),
  ('Ayacucho', 'Huanta', 'Chaca'),
  ('Ayacucho', 'Huanta', 'Huamanguilla'),
  ('Ayacucho', 'Huanta', 'Huanta'),
  ('Ayacucho', 'Huanta', 'Iguain'),
  ('Ayacucho', 'Huanta', 'Llochegua'),
  ('Ayacucho', 'Huanta', 'Luricocha'),
  ('Ayacucho', 'Huanta', 'Pucacolpa'),
  ('Ayacucho', 'Huanta', 'Putis'),
  ('Ayacucho', 'Huanta', 'Santillana'),
  ('Ayacucho', 'Huanta', 'Sivia'),
  ('Ayacucho', 'Huanta', 'Uchuraccay'),
  ('Ayacucho', 'La Mar', 'Anchihuay'),
  ('Ayacucho', 'La Mar', 'Anco'),
  ('Ayacucho', 'La Mar', 'Ayna'),
  ('Ayacucho', 'La Mar', 'Chilcas'),
  ('Ayacucho', 'La Mar', 'Chungui'),
  ('Ayacucho', 'La Mar', 'Luis Carranza'),
  ('Ayacucho', 'La Mar', 'Ninabamba'),
  ('Ayacucho', 'La Mar', 'Oronccoy'),
  ('Ayacucho', 'La Mar', 'Patibamba'),
  ('Ayacucho', 'La Mar', 'Rio Magdalena'),
  ('Ayacucho', 'La Mar', 'Samugari'),
  ('Ayacucho', 'La Mar', 'San Miguel'),
  ('Ayacucho', 'La Mar', 'Santa Rosa'),
  ('Ayacucho', 'La Mar', 'Tambo'),
  ('Ayacucho', 'La Mar', 'Union Progreso'),
  ('Ayacucho', 'Lucanas', 'Aucara'),
  ('Ayacucho', 'Lucanas', 'Cabana'),
  ('Ayacucho', 'Lucanas', 'Carmen Salcedo'),
  ('Ayacucho', 'Lucanas', 'Chaviña'),
  ('Ayacucho', 'Lucanas', 'Chipao'),
  ('Ayacucho', 'Lucanas', 'Huac-huas'),
  ('Ayacucho', 'Lucanas', 'Laramate'),
  ('Ayacucho', 'Lucanas', 'Leoncio Prado'),
  ('Ayacucho', 'Lucanas', 'Llauta'),
  ('Ayacucho', 'Lucanas', 'Lucanas'),
  ('Ayacucho', 'Lucanas', 'Ocaña'),
  ('Ayacucho', 'Lucanas', 'Otoca'),
  ('Ayacucho', 'Lucanas', 'Puquio'),
  ('Ayacucho', 'Lucanas', 'Saisa'),
  ('Ayacucho', 'Lucanas', 'San Cristobal'),
  ('Ayacucho', 'Lucanas', 'San Juan'),
  ('Ayacucho', 'Lucanas', 'San Pedro'),
  ('Ayacucho', 'Lucanas', 'San Pedro de Palco'),
  ('Ayacucho', 'Lucanas', 'Sancos'),
  ('Ayacucho', 'Lucanas', 'Santa Ana de Huaycahuacho'),
  ('Ayacucho', 'Lucanas', 'Santa Lucia'),
  ('Ayacucho', 'Parinacochas', 'Chumpi'),
  ('Ayacucho', 'Parinacochas', 'Coracora'),
  ('Ayacucho', 'Parinacochas', 'Coronel Castañeda'),
  ('Ayacucho', 'Parinacochas', 'Pacapausa'),
  ('Ayacucho', 'Parinacochas', 'Pullo'),
  ('Ayacucho', 'Parinacochas', 'Puyusca'),
  ('Ayacucho', 'Parinacochas', 'San Francisco de Ravacayco'),
  ('Ayacucho', 'Parinacochas', 'Upahuacho'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Colta'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Corculla'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Lampa'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Marcabamba'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Oyolo'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Pararca'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Pausa'),
  ('Ayacucho', 'Paucar del Sara Sara', 'San Javier de Alpabamba'),
  ('Ayacucho', 'Paucar del Sara Sara', 'San Jose de Ushua'),
  ('Ayacucho', 'Paucar del Sara Sara', 'Sara Sara'),
  ('Ayacucho', 'Sucre', 'Belen'),
  ('Ayacucho', 'Sucre', 'Chalcos'),
  ('Ayacucho', 'Sucre', 'Chilcayoc'),
  ('Ayacucho', 'Sucre', 'Huacaña'),
  ('Ayacucho', 'Sucre', 'Morcolla'),
  ('Ayacucho', 'Sucre', 'Paico'),
  ('Ayacucho', 'Sucre', 'Querobamba'),
  ('Ayacucho', 'Sucre', 'San Pedro de Larcay'),
  ('Ayacucho', 'Sucre', 'San Salvador de Quije'),
  ('Ayacucho', 'Sucre', 'Santiago de Paucaray'),
  ('Ayacucho', 'Sucre', 'Soras'),
  ('Ayacucho', 'Victor Fajardo', 'Alcamenca'),
  ('Ayacucho', 'Victor Fajardo', 'Apongo'),
  ('Ayacucho', 'Victor Fajardo', 'Asquipata'),
  ('Ayacucho', 'Victor Fajardo', 'Canaria'),
  ('Ayacucho', 'Victor Fajardo', 'Cayara'),
  ('Ayacucho', 'Victor Fajardo', 'Colca'),
  ('Ayacucho', 'Victor Fajardo', 'Huamanquiquia'),
  ('Ayacucho', 'Victor Fajardo', 'Huancapi'),
  ('Ayacucho', 'Victor Fajardo', 'Huancaraylla'),
  ('Ayacucho', 'Victor Fajardo', 'Huaya'),
  ('Ayacucho', 'Victor Fajardo', 'Sarhua'),
  ('Ayacucho', 'Victor Fajardo', 'Vilcanchos'),
  ('Ayacucho', 'Vilcas Huaman', 'Accomarca'),
  ('Ayacucho', 'Vilcas Huaman', 'Carhuanca'),
  ('Ayacucho', 'Vilcas Huaman', 'Concepcion'),
  ('Ayacucho', 'Vilcas Huaman', 'Huambalpa'),
  ('Ayacucho', 'Vilcas Huaman', 'Independencia'),
  ('Ayacucho', 'Vilcas Huaman', 'Saurama'),
  ('Ayacucho', 'Vilcas Huaman', 'Vilcas Huaman'),
  ('Ayacucho', 'Vilcas Huaman', 'Vischongo'),
  ('Cajamarca', 'Cajabamba', 'Cachachi'),
  ('Cajamarca', 'Cajabamba', 'Cajabamba'),
  ('Cajamarca', 'Cajabamba', 'Condebamba'),
  ('Cajamarca', 'Cajabamba', 'Sitacocha'),
  ('Cajamarca', 'Cajamarca', 'Asuncion'),
  ('Cajamarca', 'Cajamarca', 'Cajamarca'),
  ('Cajamarca', 'Cajamarca', 'Chetilla'),
  ('Cajamarca', 'Cajamarca', 'Cospan'),
  ('Cajamarca', 'Cajamarca', 'Encañada'),
  ('Cajamarca', 'Cajamarca', 'Jesus'),
  ('Cajamarca', 'Cajamarca', 'Llacanora'),
  ('Cajamarca', 'Cajamarca', 'Los Baños del Inca'),
  ('Cajamarca', 'Cajamarca', 'Magdalena'),
  ('Cajamarca', 'Cajamarca', 'Matara'),
  ('Cajamarca', 'Cajamarca', 'Namora'),
  ('Cajamarca', 'Cajamarca', 'San Juan'),
  ('Cajamarca', 'Celendin', 'Celendin'),
  ('Cajamarca', 'Celendin', 'Chumuch'),
  ('Cajamarca', 'Celendin', 'Cortegana'),
  ('Cajamarca', 'Celendin', 'Huasmin'),
  ('Cajamarca', 'Celendin', 'Jorge Chavez'),
  ('Cajamarca', 'Celendin', 'Jose Galvez'),
  ('Cajamarca', 'Celendin', 'La Libertad de Pallan'),
  ('Cajamarca', 'Celendin', 'Miguel Iglesias'),
  ('Cajamarca', 'Celendin', 'Oxamarca'),
  ('Cajamarca', 'Celendin', 'Sorochuco'),
  ('Cajamarca', 'Celendin', 'Sucre'),
  ('Cajamarca', 'Celendin', 'Utco'),
  ('Cajamarca', 'Chota', 'Anguia'),
  ('Cajamarca', 'Chota', 'Chadin'),
  ('Cajamarca', 'Chota', 'Chalamarca'),
  ('Cajamarca', 'Chota', 'Chiguirip'),
  ('Cajamarca', 'Chota', 'Chimban'),
  ('Cajamarca', 'Chota', 'Choropampa'),
  ('Cajamarca', 'Chota', 'Chota'),
  ('Cajamarca', 'Chota', 'Cochabamba'),
  ('Cajamarca', 'Chota', 'Conchan'),
  ('Cajamarca', 'Chota', 'Huambos'),
  ('Cajamarca', 'Chota', 'Lajas'),
  ('Cajamarca', 'Chota', 'Llama'),
  ('Cajamarca', 'Chota', 'Miracosta'),
  ('Cajamarca', 'Chota', 'Paccha'),
  ('Cajamarca', 'Chota', 'Pion'),
  ('Cajamarca', 'Chota', 'Querocoto'),
  ('Cajamarca', 'Chota', 'San Juan de Licupis'),
  ('Cajamarca', 'Chota', 'Tacabamba'),
  ('Cajamarca', 'Chota', 'Tocmoche'),
  ('Cajamarca', 'Contumaza', 'Chilete'),
  ('Cajamarca', 'Contumaza', 'Contumaza'),
  ('Cajamarca', 'Contumaza', 'Cupisnique'),
  ('Cajamarca', 'Contumaza', 'Guzmango'),
  ('Cajamarca', 'Contumaza', 'San Benito'),
  ('Cajamarca', 'Contumaza', 'Santa Cruz de Toledo'),
  ('Cajamarca', 'Contumaza', 'Tantarica'),
  ('Cajamarca', 'Contumaza', 'Yonan'),
  ('Cajamarca', 'Cutervo', 'Callayuc'),
  ('Cajamarca', 'Cutervo', 'Choros'),
  ('Cajamarca', 'Cutervo', 'Cujillo'),
  ('Cajamarca', 'Cutervo', 'Cutervo'),
  ('Cajamarca', 'Cutervo', 'La Ramada'),
  ('Cajamarca', 'Cutervo', 'Pimpingos'),
  ('Cajamarca', 'Cutervo', 'Querocotillo'),
  ('Cajamarca', 'Cutervo', 'San Andres de Cutervo'),
  ('Cajamarca', 'Cutervo', 'San Juan de Cutervo'),
  ('Cajamarca', 'Cutervo', 'San Luis de Lucma'),
  ('Cajamarca', 'Cutervo', 'Santa Cruz'),
  ('Cajamarca', 'Cutervo', 'Santo Domingo de la Capilla'),
  ('Cajamarca', 'Cutervo', 'Santo Tomas'),
  ('Cajamarca', 'Cutervo', 'Socota'),
  ('Cajamarca', 'Cutervo', 'Toribio Casanova'),
  ('Cajamarca', 'Hualgayoc', 'Bambamarca'),
  ('Cajamarca', 'Hualgayoc', 'Chugur'),
  ('Cajamarca', 'Hualgayoc', 'Hualgayoc'),
  ('Cajamarca', 'Jaen', 'Bellavista'),
  ('Cajamarca', 'Jaen', 'Chontali'),
  ('Cajamarca', 'Jaen', 'Colasay'),
  ('Cajamarca', 'Jaen', 'Huabal'),
  ('Cajamarca', 'Jaen', 'Jaen'),
  ('Cajamarca', 'Jaen', 'Las Pirias'),
  ('Cajamarca', 'Jaen', 'Pomahuaca'),
  ('Cajamarca', 'Jaen', 'Pucara'),
  ('Cajamarca', 'Jaen', 'Sallique'),
  ('Cajamarca', 'Jaen', 'San Felipe'),
  ('Cajamarca', 'Jaen', 'San Jose del Alto'),
  ('Cajamarca', 'Jaen', 'Santa Rosa'),
  ('Cajamarca', 'San Ignacio', 'Chirinos'),
  ('Cajamarca', 'San Ignacio', 'Huarango'),
  ('Cajamarca', 'San Ignacio', 'La Coipa'),
  ('Cajamarca', 'San Ignacio', 'Namballe'),
  ('Cajamarca', 'San Ignacio', 'San Ignacio'),
  ('Cajamarca', 'San Ignacio', 'San Jose de Lourdes'),
  ('Cajamarca', 'San Ignacio', 'Tabaconas'),
  ('Cajamarca', 'San Marcos', 'Chancay'),
  ('Cajamarca', 'San Marcos', 'Eduardo Villanueva'),
  ('Cajamarca', 'San Marcos', 'Gregorio Pita'),
  ('Cajamarca', 'San Marcos', 'Ichocan'),
  ('Cajamarca', 'San Marcos', 'Jose Manuel Quiroz'),
  ('Cajamarca', 'San Marcos', 'Jose Sabogal'),
  ('Cajamarca', 'San Marcos', 'Pedro Galvez'),
  ('Cajamarca', 'San Miguel', 'Bolivar'),
  ('Cajamarca', 'San Miguel', 'Calquis'),
  ('Cajamarca', 'San Miguel', 'Catilluc'),
  ('Cajamarca', 'San Miguel', 'El Prado'),
  ('Cajamarca', 'San Miguel', 'La Florida'),
  ('Cajamarca', 'San Miguel', 'Llapa'),
  ('Cajamarca', 'San Miguel', 'Nanchoc'),
  ('Cajamarca', 'San Miguel', 'Niepos'),
  ('Cajamarca', 'San Miguel', 'San Gregorio'),
  ('Cajamarca', 'San Miguel', 'San Miguel'),
  ('Cajamarca', 'San Miguel', 'San Silvestre de Cochan'),
  ('Cajamarca', 'San Miguel', 'Tongod'),
  ('Cajamarca', 'San Miguel', 'Union Agua Blanca'),
  ('Cajamarca', 'San Pablo', 'San Bernardino'),
  ('Cajamarca', 'San Pablo', 'San Luis'),
  ('Cajamarca', 'San Pablo', 'San Pablo'),
  ('Cajamarca', 'San Pablo', 'Tumbaden'),
  ('Cajamarca', 'Santa Cruz', 'Andabamba'),
  ('Cajamarca', 'Santa Cruz', 'Catache'),
  ('Cajamarca', 'Santa Cruz', 'Chancaybaños'),
  ('Cajamarca', 'Santa Cruz', 'La Esperanza'),
  ('Cajamarca', 'Santa Cruz', 'Ninabamba'),
  ('Cajamarca', 'Santa Cruz', 'Pulan'),
  ('Cajamarca', 'Santa Cruz', 'Santa Cruz'),
  ('Cajamarca', 'Santa Cruz', 'Saucepampa'),
  ('Cajamarca', 'Santa Cruz', 'Sexi'),
  ('Cajamarca', 'Santa Cruz', 'Uticyacu'),
  ('Cajamarca', 'Santa Cruz', 'Yauyucan'),
  ('Callao', 'Callao', 'Bellavista'),
  ('Callao', 'Callao', 'Callao'),
  ('Callao', 'Callao', 'Carmen de la Legua Reynoso'),
  ('Callao', 'Callao', 'La Perla'),
  ('Callao', 'Callao', 'La Punta'),
  ('Callao', 'Callao', 'Mi Peru'),
  ('Callao', 'Callao', 'Ventanilla'),
  ('Cusco', 'Acomayo', 'Acomayo'),
  ('Cusco', 'Acomayo', 'Acopia'),
  ('Cusco', 'Acomayo', 'Acos'),
  ('Cusco', 'Acomayo', 'Mosoc Llacta'),
  ('Cusco', 'Acomayo', 'Pomacanchi'),
  ('Cusco', 'Acomayo', 'Rondocan'),
  ('Cusco', 'Acomayo', 'Sangarara'),
  ('Cusco', 'Anta', 'Ancahuasi'),
  ('Cusco', 'Anta', 'Anta'),
  ('Cusco', 'Anta', 'Cachimayo'),
  ('Cusco', 'Anta', 'Chinchaypujio'),
  ('Cusco', 'Anta', 'Huarocondo'),
  ('Cusco', 'Anta', 'Limatambo'),
  ('Cusco', 'Anta', 'Mollepata'),
  ('Cusco', 'Anta', 'Pucyura'),
  ('Cusco', 'Anta', 'Zurite'),
  ('Cusco', 'Calca', 'Calca'),
  ('Cusco', 'Calca', 'Coya'),
  ('Cusco', 'Calca', 'Lamay'),
  ('Cusco', 'Calca', 'Lares'),
  ('Cusco', 'Calca', 'Pisac'),
  ('Cusco', 'Calca', 'San Salvador'),
  ('Cusco', 'Calca', 'Taray'),
  ('Cusco', 'Calca', 'Yanatile'),
  ('Cusco', 'Canas', 'Checca'),
  ('Cusco', 'Canas', 'Kunturkanki'),
  ('Cusco', 'Canas', 'Langui'),
  ('Cusco', 'Canas', 'Layo'),
  ('Cusco', 'Canas', 'Pampamarca'),
  ('Cusco', 'Canas', 'Quehue'),
  ('Cusco', 'Canas', 'Tupac Amaru'),
  ('Cusco', 'Canas', 'Yanaoca'),
  ('Cusco', 'Canchis', 'Checacupe'),
  ('Cusco', 'Canchis', 'Combapata'),
  ('Cusco', 'Canchis', 'Marangani'),
  ('Cusco', 'Canchis', 'Pitumarca'),
  ('Cusco', 'Canchis', 'San Pablo'),
  ('Cusco', 'Canchis', 'San Pedro'),
  ('Cusco', 'Canchis', 'Sicuani'),
  ('Cusco', 'Canchis', 'Tinta'),
  ('Cusco', 'Chumbivilcas', 'Capacmarca'),
  ('Cusco', 'Chumbivilcas', 'Chamaca'),
  ('Cusco', 'Chumbivilcas', 'Colquemarca'),
  ('Cusco', 'Chumbivilcas', 'Livitaca'),
  ('Cusco', 'Chumbivilcas', 'Llusco'),
  ('Cusco', 'Chumbivilcas', 'Quiñota'),
  ('Cusco', 'Chumbivilcas', 'Santo Tomas'),
  ('Cusco', 'Chumbivilcas', 'Velille'),
  ('Cusco', 'Cusco', 'Ccorca'),
  ('Cusco', 'Cusco', 'Cusco'),
  ('Cusco', 'Cusco', 'Poroy'),
  ('Cusco', 'Cusco', 'San Jeronimo'),
  ('Cusco', 'Cusco', 'San Sebastian'),
  ('Cusco', 'Cusco', 'Santiago'),
  ('Cusco', 'Cusco', 'Saylla'),
  ('Cusco', 'Cusco', 'Wanchaq'),
  ('Cusco', 'Espinar', 'Alto Pichigua'),
  ('Cusco', 'Espinar', 'Condoroma'),
  ('Cusco', 'Espinar', 'Coporaque'),
  ('Cusco', 'Espinar', 'Espinar'),
  ('Cusco', 'Espinar', 'Ocoruro'),
  ('Cusco', 'Espinar', 'Pallpata'),
  ('Cusco', 'Espinar', 'Pichigua'),
  ('Cusco', 'Espinar', 'Suyckutambo'),
  ('Cusco', 'La Convencion', 'Cielo Punco'),
  ('Cusco', 'La Convencion', 'Echarate'),
  ('Cusco', 'La Convencion', 'Huayopata'),
  ('Cusco', 'La Convencion', 'Inkawasi'),
  ('Cusco', 'La Convencion', 'Kumpirushiato'),
  ('Cusco', 'La Convencion', 'Manitea'),
  ('Cusco', 'La Convencion', 'Maranura'),
  ('Cusco', 'La Convencion', 'Megantoni'),
  ('Cusco', 'La Convencion', 'Ocobamba'),
  ('Cusco', 'La Convencion', 'Pichari'),
  ('Cusco', 'La Convencion', 'Quellouno'),
  ('Cusco', 'La Convencion', 'Quimbiri'),
  ('Cusco', 'La Convencion', 'Santa Ana'),
  ('Cusco', 'La Convencion', 'Santa Teresa'),
  ('Cusco', 'La Convencion', 'Union Asháninka'),
  ('Cusco', 'La Convencion', 'Vilcabamba'),
  ('Cusco', 'La Convencion', 'Villa Kintiarina'),
  ('Cusco', 'La Convencion', 'Villa Virgen'),
  ('Cusco', 'Paruro', 'Accha'),
  ('Cusco', 'Paruro', 'Ccapi'),
  ('Cusco', 'Paruro', 'Colcha'),
  ('Cusco', 'Paruro', 'Huanoquite'),
  ('Cusco', 'Paruro', 'Omacha'),
  ('Cusco', 'Paruro', 'Paccaritambo'),
  ('Cusco', 'Paruro', 'Paruro'),
  ('Cusco', 'Paruro', 'Pillpinto'),
  ('Cusco', 'Paruro', 'Yaurisque'),
  ('Cusco', 'Paucartambo', 'Caicay'),
  ('Cusco', 'Paucartambo', 'Challabamba'),
  ('Cusco', 'Paucartambo', 'Colquepata'),
  ('Cusco', 'Paucartambo', 'Huancarani'),
  ('Cusco', 'Paucartambo', 'Kosñipata'),
  ('Cusco', 'Paucartambo', 'Paucartambo'),
  ('Cusco', 'Quispicanchi', 'Andahuaylillas'),
  ('Cusco', 'Quispicanchi', 'Camanti'),
  ('Cusco', 'Quispicanchi', 'Ccarhuayo'),
  ('Cusco', 'Quispicanchi', 'Ccatca'),
  ('Cusco', 'Quispicanchi', 'Cusipata'),
  ('Cusco', 'Quispicanchi', 'Huaro'),
  ('Cusco', 'Quispicanchi', 'Lucre'),
  ('Cusco', 'Quispicanchi', 'Marcapata'),
  ('Cusco', 'Quispicanchi', 'Ocongate'),
  ('Cusco', 'Quispicanchi', 'Oropesa'),
  ('Cusco', 'Quispicanchi', 'Quiquijana'),
  ('Cusco', 'Quispicanchi', 'Urcos'),
  ('Cusco', 'Urubamba', 'Chinchero'),
  ('Cusco', 'Urubamba', 'Huayllabamba'),
  ('Cusco', 'Urubamba', 'Machupicchu'),
  ('Cusco', 'Urubamba', 'Maras'),
  ('Cusco', 'Urubamba', 'Ollantaytambo'),
  ('Cusco', 'Urubamba', 'Urubamba'),
  ('Cusco', 'Urubamba', 'Yucay'),
  ('Huancavelica', 'Acobamba', 'Acobamba'),
  ('Huancavelica', 'Acobamba', 'Andabamba'),
  ('Huancavelica', 'Acobamba', 'Anta'),
  ('Huancavelica', 'Acobamba', 'Caja'),
  ('Huancavelica', 'Acobamba', 'Marcas'),
  ('Huancavelica', 'Acobamba', 'Paucara'),
  ('Huancavelica', 'Acobamba', 'Pomacocha'),
  ('Huancavelica', 'Acobamba', 'Rosario'),
  ('Huancavelica', 'Angaraes', 'Anchonga'),
  ('Huancavelica', 'Angaraes', 'Callanmarca'),
  ('Huancavelica', 'Angaraes', 'Ccochaccasa'),
  ('Huancavelica', 'Angaraes', 'Chincho'),
  ('Huancavelica', 'Angaraes', 'Congalla'),
  ('Huancavelica', 'Angaraes', 'Huanca-huanca'),
  ('Huancavelica', 'Angaraes', 'Huayllay Grande'),
  ('Huancavelica', 'Angaraes', 'Julcamarca'),
  ('Huancavelica', 'Angaraes', 'Lircay'),
  ('Huancavelica', 'Angaraes', 'San Antonio de Antaparco'),
  ('Huancavelica', 'Angaraes', 'Santo Tomas de Pata'),
  ('Huancavelica', 'Angaraes', 'Secclla'),
  ('Huancavelica', 'Castrovirreyna', 'Arma'),
  ('Huancavelica', 'Castrovirreyna', 'Aurahua'),
  ('Huancavelica', 'Castrovirreyna', 'Capillas'),
  ('Huancavelica', 'Castrovirreyna', 'Castrovirreyna'),
  ('Huancavelica', 'Castrovirreyna', 'Chupamarca'),
  ('Huancavelica', 'Castrovirreyna', 'Cocas'),
  ('Huancavelica', 'Castrovirreyna', 'Huachos'),
  ('Huancavelica', 'Castrovirreyna', 'Huamatambo'),
  ('Huancavelica', 'Castrovirreyna', 'Mollepampa'),
  ('Huancavelica', 'Castrovirreyna', 'San Juan'),
  ('Huancavelica', 'Castrovirreyna', 'Santa Ana'),
  ('Huancavelica', 'Castrovirreyna', 'Tantara'),
  ('Huancavelica', 'Castrovirreyna', 'Ticrapo'),
  ('Huancavelica', 'Churcampa', 'Anco'),
  ('Huancavelica', 'Churcampa', 'Chinchihuasi'),
  ('Huancavelica', 'Churcampa', 'Churcampa'),
  ('Huancavelica', 'Churcampa', 'Cosme'),
  ('Huancavelica', 'Churcampa', 'El Carmen'),
  ('Huancavelica', 'Churcampa', 'La Merced'),
  ('Huancavelica', 'Churcampa', 'Locroja'),
  ('Huancavelica', 'Churcampa', 'Pachamarca'),
  ('Huancavelica', 'Churcampa', 'Paucarbamba'),
  ('Huancavelica', 'Churcampa', 'San Miguel de Mayocc'),
  ('Huancavelica', 'Churcampa', 'San Pedro de Coris'),
  ('Huancavelica', 'Huancavelica', 'Acobambilla'),
  ('Huancavelica', 'Huancavelica', 'Acoria'),
  ('Huancavelica', 'Huancavelica', 'Ascension'),
  ('Huancavelica', 'Huancavelica', 'Conayca'),
  ('Huancavelica', 'Huancavelica', 'Cuenca'),
  ('Huancavelica', 'Huancavelica', 'Huachocolpa'),
  ('Huancavelica', 'Huancavelica', 'Huancavelica'),
  ('Huancavelica', 'Huancavelica', 'Huando'),
  ('Huancavelica', 'Huancavelica', 'Huayllahuara'),
  ('Huancavelica', 'Huancavelica', 'Izcuchaca'),
  ('Huancavelica', 'Huancavelica', 'Laria'),
  ('Huancavelica', 'Huancavelica', 'Manta'),
  ('Huancavelica', 'Huancavelica', 'Mariscal Caceres'),
  ('Huancavelica', 'Huancavelica', 'Moya'),
  ('Huancavelica', 'Huancavelica', 'Nuevo Occoro'),
  ('Huancavelica', 'Huancavelica', 'Palca'),
  ('Huancavelica', 'Huancavelica', 'Pilchaca'),
  ('Huancavelica', 'Huancavelica', 'Vilca'),
  ('Huancavelica', 'Huancavelica', 'Yauli'),
  ('Huancavelica', 'Huaytara', 'Ayavi'),
  ('Huancavelica', 'Huaytara', 'Cordova'),
  ('Huancavelica', 'Huaytara', 'Huayacundo Arma'),
  ('Huancavelica', 'Huaytara', 'Huaytara'),
  ('Huancavelica', 'Huaytara', 'Laramarca'),
  ('Huancavelica', 'Huaytara', 'Ocoyo'),
  ('Huancavelica', 'Huaytara', 'Pilpichaca'),
  ('Huancavelica', 'Huaytara', 'Querco'),
  ('Huancavelica', 'Huaytara', 'Quito-arma'),
  ('Huancavelica', 'Huaytara', 'San Antonio de Cusicancha'),
  ('Huancavelica', 'Huaytara', 'San Francisco de Sangayaico'),
  ('Huancavelica', 'Huaytara', 'San Isidro'),
  ('Huancavelica', 'Huaytara', 'Santiago de Chocorvos'),
  ('Huancavelica', 'Huaytara', 'Santiago de Quirahuara'),
  ('Huancavelica', 'Huaytara', 'Santo Domingo de Capillas'),
  ('Huancavelica', 'Huaytara', 'Tambo'),
  ('Huancavelica', 'Tayacaja', 'Acostambo'),
  ('Huancavelica', 'Tayacaja', 'Acraquia'),
  ('Huancavelica', 'Tayacaja', 'Ahuaycha'),
  ('Huancavelica', 'Tayacaja', 'Andaymarca'),
  ('Huancavelica', 'Tayacaja', 'Cochabamba'),
  ('Huancavelica', 'Tayacaja', 'Colcabamba'),
  ('Huancavelica', 'Tayacaja', 'Daniel Hernandez'),
  ('Huancavelica', 'Tayacaja', 'Huachocolpa'),
  ('Huancavelica', 'Tayacaja', 'Huaribamba'),
  ('Huancavelica', 'Tayacaja', 'Lambras'),
  ('Huancavelica', 'Tayacaja', 'Pampas'),
  ('Huancavelica', 'Tayacaja', 'Pazos'),
  ('Huancavelica', 'Tayacaja', 'Pichos'),
  ('Huancavelica', 'Tayacaja', 'Quichuas'),
  ('Huancavelica', 'Tayacaja', 'Quishuar'),
  ('Huancavelica', 'Tayacaja', 'Roble'),
  ('Huancavelica', 'Tayacaja', 'Salcabamba'),
  ('Huancavelica', 'Tayacaja', 'Salcahuasi'),
  ('Huancavelica', 'Tayacaja', 'San Marcos de Rocchac'),
  ('Huancavelica', 'Tayacaja', 'Santiago de Tucuma'),
  ('Huancavelica', 'Tayacaja', 'Surcubamba'),
  ('Huancavelica', 'Tayacaja', 'Tintay Puncu'),
  ('Huancavelica', 'Tayacaja', 'Ñahuimpuquio'),
  ('Huánuco', 'Ambo', 'Ambo'),
  ('Huánuco', 'Ambo', 'Cayna'),
  ('Huánuco', 'Ambo', 'Colpas'),
  ('Huánuco', 'Ambo', 'Conchamarca'),
  ('Huánuco', 'Ambo', 'Huacar'),
  ('Huánuco', 'Ambo', 'San Francisco'),
  ('Huánuco', 'Ambo', 'San Rafael'),
  ('Huánuco', 'Ambo', 'Tomay Kichwa'),
  ('Huánuco', 'Dos de Mayo', 'Chuquis'),
  ('Huánuco', 'Dos de Mayo', 'La Union'),
  ('Huánuco', 'Dos de Mayo', 'Marias'),
  ('Huánuco', 'Dos de Mayo', 'Pachas'),
  ('Huánuco', 'Dos de Mayo', 'Quivilla'),
  ('Huánuco', 'Dos de Mayo', 'Ripan'),
  ('Huánuco', 'Dos de Mayo', 'Shunqui'),
  ('Huánuco', 'Dos de Mayo', 'Sillapata'),
  ('Huánuco', 'Dos de Mayo', 'Yanas'),
  ('Huánuco', 'Huacaybamba', 'Canchabamba'),
  ('Huánuco', 'Huacaybamba', 'Cochabamba'),
  ('Huánuco', 'Huacaybamba', 'Huacaybamba'),
  ('Huánuco', 'Huacaybamba', 'Pinra'),
  ('Huánuco', 'Huamalies', 'Arancay'),
  ('Huánuco', 'Huamalies', 'Chavin de Pariarca'),
  ('Huánuco', 'Huamalies', 'Jacas Grande'),
  ('Huánuco', 'Huamalies', 'Jircan'),
  ('Huánuco', 'Huamalies', 'Llata'),
  ('Huánuco', 'Huamalies', 'Miraflores'),
  ('Huánuco', 'Huamalies', 'Monzon'),
  ('Huánuco', 'Huamalies', 'Punchao'),
  ('Huánuco', 'Huamalies', 'Puños'),
  ('Huánuco', 'Huamalies', 'Singa'),
  ('Huánuco', 'Huamalies', 'Tantamayo'),
  ('Huánuco', 'Huánuco', 'Amarilis'),
  ('Huánuco', 'Huánuco', 'Chinchao'),
  ('Huánuco', 'Huánuco', 'Churubamba'),
  ('Huánuco', 'Huánuco', 'Huánuco'),
  ('Huánuco', 'Huánuco', 'Margos'),
  ('Huánuco', 'Huánuco', 'Pillco Marca'),
  ('Huánuco', 'Huánuco', 'Quisqui'),
  ('Huánuco', 'Huánuco', 'San Francisco de Cayran'),
  ('Huánuco', 'Huánuco', 'San Pablo de Pillao'),
  ('Huánuco', 'Huánuco', 'San Pedro de Chaulan'),
  ('Huánuco', 'Huánuco', 'Santa Maria del Valle'),
  ('Huánuco', 'Huánuco', 'Yacus'),
  ('Huánuco', 'Huánuco', 'Yarumayo'),
  ('Huánuco', 'Lauricocha', 'Baños'),
  ('Huánuco', 'Lauricocha', 'Jesus'),
  ('Huánuco', 'Lauricocha', 'Jivia'),
  ('Huánuco', 'Lauricocha', 'Queropalca'),
  ('Huánuco', 'Lauricocha', 'Rondos'),
  ('Huánuco', 'Lauricocha', 'San Francisco de Asis'),
  ('Huánuco', 'Lauricocha', 'San Miguel de Cauri'),
  ('Huánuco', 'Leoncio Prado', 'Castillo Grande'),
  ('Huánuco', 'Leoncio Prado', 'Daniel Alomias Robles'),
  ('Huánuco', 'Leoncio Prado', 'Hermilio Valdizan'),
  ('Huánuco', 'Leoncio Prado', 'Jose Crespo y Castillo'),
  ('Huánuco', 'Leoncio Prado', 'Luyando'),
  ('Huánuco', 'Leoncio Prado', 'Mariano Damaso Beraun'),
  ('Huánuco', 'Leoncio Prado', 'Pucayacu'),
  ('Huánuco', 'Leoncio Prado', 'Pueblo Nuevo'),
  ('Huánuco', 'Leoncio Prado', 'Rupa-rupa'),
  ('Huánuco', 'Leoncio Prado', 'Santo Domingo de Anda'),
  ('Huánuco', 'Marañon', 'Cholon'),
  ('Huánuco', 'Marañon', 'Huacrachuco'),
  ('Huánuco', 'Marañon', 'La Morada'),
  ('Huánuco', 'Marañon', 'San Buenaventura'),
  ('Huánuco', 'Marañon', 'Santa Rosa de Alto Yanajanca'),
  ('Huánuco', 'Pachitea', 'Chaglla'),
  ('Huánuco', 'Pachitea', 'Molino'),
  ('Huánuco', 'Pachitea', 'Panao'),
  ('Huánuco', 'Pachitea', 'Umari'),
  ('Huánuco', 'Puerto Inca', 'Codo del Pozuzo'),
  ('Huánuco', 'Puerto Inca', 'Honoria'),
  ('Huánuco', 'Puerto Inca', 'Puerto Inca'),
  ('Huánuco', 'Puerto Inca', 'Tournavista'),
  ('Huánuco', 'Puerto Inca', 'Yuyapichis'),
  ('Huánuco', 'Yarowilca', 'Aparicio Pomares'),
  ('Huánuco', 'Yarowilca', 'Cahuac'),
  ('Huánuco', 'Yarowilca', 'Chacabamba'),
  ('Huánuco', 'Yarowilca', 'Chavinillo'),
  ('Huánuco', 'Yarowilca', 'Choras'),
  ('Huánuco', 'Yarowilca', 'Jacas Chico'),
  ('Huánuco', 'Yarowilca', 'Obas'),
  ('Huánuco', 'Yarowilca', 'Pampamarca'),
  ('Ica', 'Chincha', 'Alto Laran'),
  ('Ica', 'Chincha', 'Chavin'),
  ('Ica', 'Chincha', 'Chincha Alta'),
  ('Ica', 'Chincha', 'Chincha Baja'),
  ('Ica', 'Chincha', 'El Carmen'),
  ('Ica', 'Chincha', 'Grocio Prado'),
  ('Ica', 'Chincha', 'Pueblo Nuevo'),
  ('Ica', 'Chincha', 'San Juan de Yanac'),
  ('Ica', 'Chincha', 'San Pedro de Huacarpana'),
  ('Ica', 'Chincha', 'Sunampe'),
  ('Ica', 'Chincha', 'Tambo de Mora'),
  ('Ica', 'Ica', 'Ica'),
  ('Ica', 'Ica', 'La Tinguiña'),
  ('Ica', 'Ica', 'Los Aquijes'),
  ('Ica', 'Ica', 'Ocucaje'),
  ('Ica', 'Ica', 'Pachacutec'),
  ('Ica', 'Ica', 'Parcona'),
  ('Ica', 'Ica', 'Pueblo Nuevo'),
  ('Ica', 'Ica', 'Salas'),
  ('Ica', 'Ica', 'San Jose de los Molinos'),
  ('Ica', 'Ica', 'San Juan Bautista'),
  ('Ica', 'Ica', 'Santiago'),
  ('Ica', 'Ica', 'Subtanjalla'),
  ('Ica', 'Ica', 'Tate'),
  ('Ica', 'Ica', 'Yauca del Rosario'),
  ('Ica', 'Nazca', 'Changuillo'),
  ('Ica', 'Nazca', 'El Ingenio'),
  ('Ica', 'Nazca', 'Marcona'),
  ('Ica', 'Nazca', 'Nazca'),
  ('Ica', 'Nazca', 'Vista Alegre'),
  ('Ica', 'Palpa', 'Llipata'),
  ('Ica', 'Palpa', 'Palpa'),
  ('Ica', 'Palpa', 'Rio Grande'),
  ('Ica', 'Palpa', 'Santa Cruz'),
  ('Ica', 'Palpa', 'Tibillo'),
  ('Ica', 'Pisco', 'Huancano'),
  ('Ica', 'Pisco', 'Humay'),
  ('Ica', 'Pisco', 'Independencia'),
  ('Ica', 'Pisco', 'Paracas'),
  ('Ica', 'Pisco', 'Pisco'),
  ('Ica', 'Pisco', 'San Andres'),
  ('Ica', 'Pisco', 'San Clemente'),
  ('Ica', 'Pisco', 'Tupac Amaru Inca'),
  ('Junín', 'Chanchamayo', 'Chanchamayo'),
  ('Junín', 'Chanchamayo', 'Perene'),
  ('Junín', 'Chanchamayo', 'Pichanaqui'),
  ('Junín', 'Chanchamayo', 'San Luis de Shuaro'),
  ('Junín', 'Chanchamayo', 'San Ramon'),
  ('Junín', 'Chanchamayo', 'Vitoc'),
  ('Junín', 'Chupaca', 'Ahuac'),
  ('Junín', 'Chupaca', 'Chongos Bajo'),
  ('Junín', 'Chupaca', 'Chupaca'),
  ('Junín', 'Chupaca', 'Huachac'),
  ('Junín', 'Chupaca', 'Huamancaca Chico'),
  ('Junín', 'Chupaca', 'San Juan de Jarpa'),
  ('Junín', 'Chupaca', 'San Juan de Yscos'),
  ('Junín', 'Chupaca', 'Tres de Diciembre'),
  ('Junín', 'Chupaca', 'Yanacancha'),
  ('Junín', 'Concepcion', 'Aco'),
  ('Junín', 'Concepcion', 'Andamarca'),
  ('Junín', 'Concepcion', 'Chambara'),
  ('Junín', 'Concepcion', 'Cochas'),
  ('Junín', 'Concepcion', 'Comas'),
  ('Junín', 'Concepcion', 'Concepcion'),
  ('Junín', 'Concepcion', 'Heroinas Toledo'),
  ('Junín', 'Concepcion', 'Manzanares'),
  ('Junín', 'Concepcion', 'Mariscal Castilla'),
  ('Junín', 'Concepcion', 'Matahuasi'),
  ('Junín', 'Concepcion', 'Mito'),
  ('Junín', 'Concepcion', 'Nueve de Julio'),
  ('Junín', 'Concepcion', 'Orcotuna'),
  ('Junín', 'Concepcion', 'San Jose de Quero'),
  ('Junín', 'Concepcion', 'Santa Rosa de Ocopa'),
  ('Junín', 'Huancayo', 'Carhuacallanga'),
  ('Junín', 'Huancayo', 'Chacapampa'),
  ('Junín', 'Huancayo', 'Chicche'),
  ('Junín', 'Huancayo', 'Chilca'),
  ('Junín', 'Huancayo', 'Chongos Alto'),
  ('Junín', 'Huancayo', 'Chupuro'),
  ('Junín', 'Huancayo', 'Colca'),
  ('Junín', 'Huancayo', 'Cullhuas'),
  ('Junín', 'Huancayo', 'El Tambo'),
  ('Junín', 'Huancayo', 'Huacrapuquio'),
  ('Junín', 'Huancayo', 'Hualhuas'),
  ('Junín', 'Huancayo', 'Huancan'),
  ('Junín', 'Huancayo', 'Huancayo'),
  ('Junín', 'Huancayo', 'Huasicancha'),
  ('Junín', 'Huancayo', 'Huayucachi'),
  ('Junín', 'Huancayo', 'Ingenio'),
  ('Junín', 'Huancayo', 'Pariahuanca'),
  ('Junín', 'Huancayo', 'Pilcomayo'),
  ('Junín', 'Huancayo', 'Pucara'),
  ('Junín', 'Huancayo', 'Quichuay'),
  ('Junín', 'Huancayo', 'Quilcas'),
  ('Junín', 'Huancayo', 'San Agustin'),
  ('Junín', 'Huancayo', 'San Jeronimo de Tunan'),
  ('Junín', 'Huancayo', 'Santo Domingo de Acobamba'),
  ('Junín', 'Huancayo', 'Sapallanga'),
  ('Junín', 'Huancayo', 'Saño'),
  ('Junín', 'Huancayo', 'Sicaya'),
  ('Junín', 'Huancayo', 'Viques'),
  ('Junín', 'Jauja', 'Acolla'),
  ('Junín', 'Jauja', 'Apata'),
  ('Junín', 'Jauja', 'Ataura'),
  ('Junín', 'Jauja', 'Canchayllo'),
  ('Junín', 'Jauja', 'Curicaca'),
  ('Junín', 'Jauja', 'El Mantaro'),
  ('Junín', 'Jauja', 'Huamali'),
  ('Junín', 'Jauja', 'Huaripampa'),
  ('Junín', 'Jauja', 'Huertas'),
  ('Junín', 'Jauja', 'Janjaillo'),
  ('Junín', 'Jauja', 'Jauja'),
  ('Junín', 'Jauja', 'Julcan'),
  ('Junín', 'Jauja', 'Leonor Ordoñez'),
  ('Junín', 'Jauja', 'Llocllapampa'),
  ('Junín', 'Jauja', 'Marco'),
  ('Junín', 'Jauja', 'Masma'),
  ('Junín', 'Jauja', 'Masma Chicche'),
  ('Junín', 'Jauja', 'Molinos'),
  ('Junín', 'Jauja', 'Monobamba'),
  ('Junín', 'Jauja', 'Muqui'),
  ('Junín', 'Jauja', 'Muquiyauyo'),
  ('Junín', 'Jauja', 'Paca'),
  ('Junín', 'Jauja', 'Paccha'),
  ('Junín', 'Jauja', 'Pancan'),
  ('Junín', 'Jauja', 'Parco'),
  ('Junín', 'Jauja', 'Pomacancha'),
  ('Junín', 'Jauja', 'Ricran'),
  ('Junín', 'Jauja', 'San Lorenzo'),
  ('Junín', 'Jauja', 'San Pedro de Chunan'),
  ('Junín', 'Jauja', 'Sausa'),
  ('Junín', 'Jauja', 'Sincos'),
  ('Junín', 'Jauja', 'Tunan Marca'),
  ('Junín', 'Jauja', 'Yauli'),
  ('Junín', 'Jauja', 'Yauyos'),
  ('Junín', 'Junín', 'Carhuamayo'),
  ('Junín', 'Junín', 'Junín'),
  ('Junín', 'Junín', 'Ondores'),
  ('Junín', 'Junín', 'Ulcumayo'),
  ('Junín', 'Satipo', 'Coviriali'),
  ('Junín', 'Satipo', 'Llaylla'),
  ('Junín', 'Satipo', 'Mazamari'),
  ('Junín', 'Satipo', 'Pampa Hermosa'),
  ('Junín', 'Satipo', 'Pangoa'),
  ('Junín', 'Satipo', 'Rio Negro'),
  ('Junín', 'Satipo', 'Rio Tambo'),
  ('Junín', 'Satipo', 'Satipo'),
  ('Junín', 'Satipo', 'Vizcatan del Ene'),
  ('Junín', 'Tarma', 'Acobamba'),
  ('Junín', 'Tarma', 'Huaricolca'),
  ('Junín', 'Tarma', 'Huasahuasi'),
  ('Junín', 'Tarma', 'La Union'),
  ('Junín', 'Tarma', 'Palca'),
  ('Junín', 'Tarma', 'Palcamayo'),
  ('Junín', 'Tarma', 'San Pedro de Cajas'),
  ('Junín', 'Tarma', 'Tapo'),
  ('Junín', 'Tarma', 'Tarma'),
  ('Junín', 'Yauli', 'Chacapalpa'),
  ('Junín', 'Yauli', 'Huay-huay'),
  ('Junín', 'Yauli', 'La Oroya'),
  ('Junín', 'Yauli', 'Marcapomacocha'),
  ('Junín', 'Yauli', 'Morococha'),
  ('Junín', 'Yauli', 'Paccha'),
  ('Junín', 'Yauli', 'Santa Barbara de Carhuacayan'),
  ('Junín', 'Yauli', 'Santa Rosa de Sacco'),
  ('Junín', 'Yauli', 'Suitucancha'),
  ('Junín', 'Yauli', 'Yauli'),
  ('La Libertad', 'Ascope', 'Ascope'),
  ('La Libertad', 'Ascope', 'Casa Grande'),
  ('La Libertad', 'Ascope', 'Chicama'),
  ('La Libertad', 'Ascope', 'Chocope'),
  ('La Libertad', 'Ascope', 'Magdalena de Cao'),
  ('La Libertad', 'Ascope', 'Paijan'),
  ('La Libertad', 'Ascope', 'Razuri'),
  ('La Libertad', 'Ascope', 'Santiago de Cao'),
  ('La Libertad', 'Bolivar', 'Bambamarca'),
  ('La Libertad', 'Bolivar', 'Bolivar'),
  ('La Libertad', 'Bolivar', 'Condormarca'),
  ('La Libertad', 'Bolivar', 'Longotea'),
  ('La Libertad', 'Bolivar', 'Uchumarca'),
  ('La Libertad', 'Bolivar', 'Ucuncha'),
  ('La Libertad', 'Chepen', 'Chepen'),
  ('La Libertad', 'Chepen', 'Pacanga'),
  ('La Libertad', 'Chepen', 'Pueblo Nuevo'),
  ('La Libertad', 'Gran Chimu', 'Cascas'),
  ('La Libertad', 'Gran Chimu', 'Lucma'),
  ('La Libertad', 'Gran Chimu', 'Marmot'),
  ('La Libertad', 'Gran Chimu', 'Sayapullo'),
  ('La Libertad', 'Julcan', 'Calamarca'),
  ('La Libertad', 'Julcan', 'Carabamba'),
  ('La Libertad', 'Julcan', 'Huaso'),
  ('La Libertad', 'Julcan', 'Julcan'),
  ('La Libertad', 'Otuzco', 'Agallpampa'),
  ('La Libertad', 'Otuzco', 'Charat'),
  ('La Libertad', 'Otuzco', 'Huaranchal'),
  ('La Libertad', 'Otuzco', 'La Cuesta'),
  ('La Libertad', 'Otuzco', 'Mache'),
  ('La Libertad', 'Otuzco', 'Otuzco'),
  ('La Libertad', 'Otuzco', 'Paranday'),
  ('La Libertad', 'Otuzco', 'Salpo'),
  ('La Libertad', 'Otuzco', 'Sinsicap'),
  ('La Libertad', 'Otuzco', 'Usquil'),
  ('La Libertad', 'Pacasmayo', 'Guadalupe'),
  ('La Libertad', 'Pacasmayo', 'Jequetepeque'),
  ('La Libertad', 'Pacasmayo', 'Pacasmayo'),
  ('La Libertad', 'Pacasmayo', 'San Jose'),
  ('La Libertad', 'Pacasmayo', 'San Pedro de Lloc'),
  ('La Libertad', 'Pataz', 'Buldibuyo'),
  ('La Libertad', 'Pataz', 'Chillia'),
  ('La Libertad', 'Pataz', 'Huancaspata'),
  ('La Libertad', 'Pataz', 'Huaylillas'),
  ('La Libertad', 'Pataz', 'Huayo'),
  ('La Libertad', 'Pataz', 'Ongon'),
  ('La Libertad', 'Pataz', 'Parcoy'),
  ('La Libertad', 'Pataz', 'Pataz'),
  ('La Libertad', 'Pataz', 'Pias'),
  ('La Libertad', 'Pataz', 'Santiago de Challas'),
  ('La Libertad', 'Pataz', 'Taurija'),
  ('La Libertad', 'Pataz', 'Tayabamba'),
  ('La Libertad', 'Pataz', 'Urpay'),
  ('La Libertad', 'Sanchez Carrion', 'Chugay'),
  ('La Libertad', 'Sanchez Carrion', 'Cochorco'),
  ('La Libertad', 'Sanchez Carrion', 'Curgos'),
  ('La Libertad', 'Sanchez Carrion', 'Huamachuco'),
  ('La Libertad', 'Sanchez Carrion', 'Marcabal'),
  ('La Libertad', 'Sanchez Carrion', 'Sanagoran'),
  ('La Libertad', 'Sanchez Carrion', 'Sarin'),
  ('La Libertad', 'Sanchez Carrion', 'Sartimbamba'),
  ('La Libertad', 'Santiago de Chuco', 'Angasmarca'),
  ('La Libertad', 'Santiago de Chuco', 'Cachicadan'),
  ('La Libertad', 'Santiago de Chuco', 'Mollebamba'),
  ('La Libertad', 'Santiago de Chuco', 'Mollepata'),
  ('La Libertad', 'Santiago de Chuco', 'Quiruvilca'),
  ('La Libertad', 'Santiago de Chuco', 'Santa Cruz de Chuca'),
  ('La Libertad', 'Santiago de Chuco', 'Santiago de Chuco'),
  ('La Libertad', 'Santiago de Chuco', 'Sitabamba'),
  ('La Libertad', 'Trujillo', 'El Porvenir'),
  ('La Libertad', 'Trujillo', 'Florencia de Mora'),
  ('La Libertad', 'Trujillo', 'Huanchaco'),
  ('La Libertad', 'Trujillo', 'La Esperanza'),
  ('La Libertad', 'Trujillo', 'Laredo'),
  ('La Libertad', 'Trujillo', 'Moche'),
  ('La Libertad', 'Trujillo', 'Poroto'),
  ('La Libertad', 'Trujillo', 'Salaverry'),
  ('La Libertad', 'Trujillo', 'Simbal'),
  ('La Libertad', 'Trujillo', 'Trujillo'),
  ('La Libertad', 'Trujillo', 'Victor Larco Herrera'),
  ('La Libertad', 'Viru', 'Chao'),
  ('La Libertad', 'Viru', 'Guadalupito'),
  ('La Libertad', 'Viru', 'Viru'),
  ('Lambayeque', 'Chiclayo', 'Cayalti'),
  ('Lambayeque', 'Chiclayo', 'Chiclayo'),
  ('Lambayeque', 'Chiclayo', 'Chongoyape'),
  ('Lambayeque', 'Chiclayo', 'Eten'),
  ('Lambayeque', 'Chiclayo', 'Eten Puerto'),
  ('Lambayeque', 'Chiclayo', 'Jose Leonardo Ortiz'),
  ('Lambayeque', 'Chiclayo', 'La Victoria'),
  ('Lambayeque', 'Chiclayo', 'Lagunas'),
  ('Lambayeque', 'Chiclayo', 'Monsefu'),
  ('Lambayeque', 'Chiclayo', 'Nueva Arica'),
  ('Lambayeque', 'Chiclayo', 'Oyotun'),
  ('Lambayeque', 'Chiclayo', 'Patapo'),
  ('Lambayeque', 'Chiclayo', 'Picsi'),
  ('Lambayeque', 'Chiclayo', 'Pimentel'),
  ('Lambayeque', 'Chiclayo', 'Pomalca'),
  ('Lambayeque', 'Chiclayo', 'Pucala'),
  ('Lambayeque', 'Chiclayo', 'Reque'),
  ('Lambayeque', 'Chiclayo', 'Santa Rosa'),
  ('Lambayeque', 'Chiclayo', 'Saña'),
  ('Lambayeque', 'Chiclayo', 'Tuman'),
  ('Lambayeque', 'Ferreñafe', 'Cañaris'),
  ('Lambayeque', 'Ferreñafe', 'Ferreñafe'),
  ('Lambayeque', 'Ferreñafe', 'Incahuasi'),
  ('Lambayeque', 'Ferreñafe', 'Manuel Antonio Mesones Muro'),
  ('Lambayeque', 'Ferreñafe', 'Pitipo'),
  ('Lambayeque', 'Ferreñafe', 'Pueblo Nuevo'),
  ('Lambayeque', 'Lambayeque', 'Chochope'),
  ('Lambayeque', 'Lambayeque', 'Illimo'),
  ('Lambayeque', 'Lambayeque', 'Jayanca'),
  ('Lambayeque', 'Lambayeque', 'Lambayeque'),
  ('Lambayeque', 'Lambayeque', 'Mochumi'),
  ('Lambayeque', 'Lambayeque', 'Morrope'),
  ('Lambayeque', 'Lambayeque', 'Motupe'),
  ('Lambayeque', 'Lambayeque', 'Olmos'),
  ('Lambayeque', 'Lambayeque', 'Pacora'),
  ('Lambayeque', 'Lambayeque', 'Salas'),
  ('Lambayeque', 'Lambayeque', 'San Jose'),
  ('Lambayeque', 'Lambayeque', 'Tucume'),
  ('Lima', 'Barranca', 'Barranca'),
  ('Lima', 'Barranca', 'Paramonga'),
  ('Lima', 'Barranca', 'Pativilca'),
  ('Lima', 'Barranca', 'Supe'),
  ('Lima', 'Barranca', 'Supe Puerto'),
  ('Lima', 'Cajatambo', 'Cajatambo'),
  ('Lima', 'Cajatambo', 'Copa'),
  ('Lima', 'Cajatambo', 'Gorgor'),
  ('Lima', 'Cajatambo', 'Huancapon'),
  ('Lima', 'Cajatambo', 'Manas'),
  ('Lima', 'Canta', 'Arahuay'),
  ('Lima', 'Canta', 'Canta'),
  ('Lima', 'Canta', 'Huamantanga'),
  ('Lima', 'Canta', 'Huaros'),
  ('Lima', 'Canta', 'Lachaqui'),
  ('Lima', 'Canta', 'San Buenaventura'),
  ('Lima', 'Canta', 'Santa Rosa de Quives'),
  ('Lima', 'Cañete', 'Asia'),
  ('Lima', 'Cañete', 'Calango'),
  ('Lima', 'Cañete', 'Cerro Azul'),
  ('Lima', 'Cañete', 'Chilca'),
  ('Lima', 'Cañete', 'Coayllo'),
  ('Lima', 'Cañete', 'Imperial'),
  ('Lima', 'Cañete', 'Lunahuana'),
  ('Lima', 'Cañete', 'Mala'),
  ('Lima', 'Cañete', 'Nuevo Imperial'),
  ('Lima', 'Cañete', 'Pacaran'),
  ('Lima', 'Cañete', 'Quilmana'),
  ('Lima', 'Cañete', 'San Antonio'),
  ('Lima', 'Cañete', 'San Luis'),
  ('Lima', 'Cañete', 'San Vicente de Cañete'),
  ('Lima', 'Cañete', 'Santa Cruz de Flores'),
  ('Lima', 'Cañete', 'Zuñiga'),
  ('Lima', 'Huaral', 'Atavillos Alto'),
  ('Lima', 'Huaral', 'Atavillos Bajo'),
  ('Lima', 'Huaral', 'Aucallama'),
  ('Lima', 'Huaral', 'Chancay'),
  ('Lima', 'Huaral', 'Huaral'),
  ('Lima', 'Huaral', 'Ihuari'),
  ('Lima', 'Huaral', 'Lampian'),
  ('Lima', 'Huaral', 'Pacaraos'),
  ('Lima', 'Huaral', 'San Miguel de Acos'),
  ('Lima', 'Huaral', 'Santa Cruz de Andamarca'),
  ('Lima', 'Huaral', 'Sumbilca'),
  ('Lima', 'Huaral', 'Veintisiete de Noviembre'),
  ('Lima', 'Huarochiri', 'Antioquia'),
  ('Lima', 'Huarochiri', 'Callahuanca'),
  ('Lima', 'Huarochiri', 'Carampoma'),
  ('Lima', 'Huarochiri', 'Chicla'),
  ('Lima', 'Huarochiri', 'Cuenca'),
  ('Lima', 'Huarochiri', 'Huachupampa'),
  ('Lima', 'Huarochiri', 'Huanza'),
  ('Lima', 'Huarochiri', 'Huarochiri'),
  ('Lima', 'Huarochiri', 'Lahuaytambo'),
  ('Lima', 'Huarochiri', 'Langa'),
  ('Lima', 'Huarochiri', 'Laraos'),
  ('Lima', 'Huarochiri', 'Mariatana'),
  ('Lima', 'Huarochiri', 'Matucana'),
  ('Lima', 'Huarochiri', 'Ricardo Palma'),
  ('Lima', 'Huarochiri', 'San Andres de Tupicocha'),
  ('Lima', 'Huarochiri', 'San Antonio'),
  ('Lima', 'Huarochiri', 'San Bartolome'),
  ('Lima', 'Huarochiri', 'San Damian'),
  ('Lima', 'Huarochiri', 'San Juan de Iris'),
  ('Lima', 'Huarochiri', 'San Juan de Tantaranche'),
  ('Lima', 'Huarochiri', 'San Lorenzo de Quinti'),
  ('Lima', 'Huarochiri', 'San Mateo'),
  ('Lima', 'Huarochiri', 'San Mateo de Otao'),
  ('Lima', 'Huarochiri', 'San Pedro de Casta'),
  ('Lima', 'Huarochiri', 'San Pedro de Huancayre'),
  ('Lima', 'Huarochiri', 'Sangallaya'),
  ('Lima', 'Huarochiri', 'Santa Cruz de Cocachacra'),
  ('Lima', 'Huarochiri', 'Santa Eulalia'),
  ('Lima', 'Huarochiri', 'Santiago de Anchucaya'),
  ('Lima', 'Huarochiri', 'Santiago de Tuna'),
  ('Lima', 'Huarochiri', 'Santo Domingo de los Olleros'),
  ('Lima', 'Huarochiri', 'Surco'),
  ('Lima', 'Huaura', 'Ambar'),
  ('Lima', 'Huaura', 'Caleta de Carquin'),
  ('Lima', 'Huaura', 'Checras'),
  ('Lima', 'Huaura', 'Huacho'),
  ('Lima', 'Huaura', 'Hualmay'),
  ('Lima', 'Huaura', 'Huaura'),
  ('Lima', 'Huaura', 'Leoncio Prado'),
  ('Lima', 'Huaura', 'Paccho'),
  ('Lima', 'Huaura', 'Santa Leonor'),
  ('Lima', 'Huaura', 'Santa Maria'),
  ('Lima', 'Huaura', 'Sayan'),
  ('Lima', 'Huaura', 'Vegueta'),
  ('Lima', 'Lima', 'Ancon'),
  ('Lima', 'Lima', 'Ate'),
  ('Lima', 'Lima', 'Barranco'),
  ('Lima', 'Lima', 'Breña'),
  ('Lima', 'Lima', 'Carabayllo'),
  ('Lima', 'Lima', 'Chaclacayo'),
  ('Lima', 'Lima', 'Chorrillos'),
  ('Lima', 'Lima', 'Cieneguilla'),
  ('Lima', 'Lima', 'Comas'),
  ('Lima', 'Lima', 'El Agustino'),
  ('Lima', 'Lima', 'Independencia'),
  ('Lima', 'Lima', 'Jesus Maria'),
  ('Lima', 'Lima', 'La Molina'),
  ('Lima', 'Lima', 'La Victoria'),
  ('Lima', 'Lima', 'Lima'),
  ('Lima', 'Lima', 'Lince'),
  ('Lima', 'Lima', 'Los Olivos'),
  ('Lima', 'Lima', 'Lurigancho'),
  ('Lima', 'Lima', 'Lurin'),
  ('Lima', 'Lima', 'Magdalena del Mar'),
  ('Lima', 'Lima', 'Miraflores'),
  ('Lima', 'Lima', 'Pachacamac'),
  ('Lima', 'Lima', 'Pucusana'),
  ('Lima', 'Lima', 'Pueblo Libre'),
  ('Lima', 'Lima', 'Puente Piedra'),
  ('Lima', 'Lima', 'Punta Hermosa'),
  ('Lima', 'Lima', 'Punta Negra'),
  ('Lima', 'Lima', 'Rimac'),
  ('Lima', 'Lima', 'San Bartolo'),
  ('Lima', 'Lima', 'San Borja'),
  ('Lima', 'Lima', 'San Isidro'),
  ('Lima', 'Lima', 'San Juan de Lurigancho'),
  ('Lima', 'Lima', 'San Juan de Miraflores'),
  ('Lima', 'Lima', 'San Luis'),
  ('Lima', 'Lima', 'San Martin de Porres'),
  ('Lima', 'Lima', 'San Miguel'),
  ('Lima', 'Lima', 'Santa Anita'),
  ('Lima', 'Lima', 'Santa Maria de Huachipa'),
  ('Lima', 'Lima', 'Santa Maria del Mar'),
  ('Lima', 'Lima', 'Santa Rosa'),
  ('Lima', 'Lima', 'Santiago de Surco'),
  ('Lima', 'Lima', 'Surquillo'),
  ('Lima', 'Lima', 'Villa El Salvador'),
  ('Lima', 'Lima', 'Villa Maria del Triunfo'),
  ('Lima', 'Oyon', 'Andajes'),
  ('Lima', 'Oyon', 'Caujul'),
  ('Lima', 'Oyon', 'Cochamarca'),
  ('Lima', 'Oyon', 'Navan'),
  ('Lima', 'Oyon', 'Oyon'),
  ('Lima', 'Oyon', 'Pachangara'),
  ('Lima', 'Yauyos', 'Alis'),
  ('Lima', 'Yauyos', 'Ayauca'),
  ('Lima', 'Yauyos', 'Ayaviri'),
  ('Lima', 'Yauyos', 'Azangaro'),
  ('Lima', 'Yauyos', 'Cacra'),
  ('Lima', 'Yauyos', 'Carania'),
  ('Lima', 'Yauyos', 'Catahuasi'),
  ('Lima', 'Yauyos', 'Chocos'),
  ('Lima', 'Yauyos', 'Cochas'),
  ('Lima', 'Yauyos', 'Colonia'),
  ('Lima', 'Yauyos', 'Hongos'),
  ('Lima', 'Yauyos', 'Huampara'),
  ('Lima', 'Yauyos', 'Huancaya'),
  ('Lima', 'Yauyos', 'Huangascar'),
  ('Lima', 'Yauyos', 'Huantan'),
  ('Lima', 'Yauyos', 'Huañec'),
  ('Lima', 'Yauyos', 'Laraos'),
  ('Lima', 'Yauyos', 'Lincha'),
  ('Lima', 'Yauyos', 'Madean'),
  ('Lima', 'Yauyos', 'Miraflores'),
  ('Lima', 'Yauyos', 'Omas'),
  ('Lima', 'Yauyos', 'Putinza'),
  ('Lima', 'Yauyos', 'Quinches'),
  ('Lima', 'Yauyos', 'Quinocay'),
  ('Lima', 'Yauyos', 'San Joaquin'),
  ('Lima', 'Yauyos', 'San Pedro de Pilas'),
  ('Lima', 'Yauyos', 'Tanta'),
  ('Lima', 'Yauyos', 'Tauripampa'),
  ('Lima', 'Yauyos', 'Tomas'),
  ('Lima', 'Yauyos', 'Tupe'),
  ('Lima', 'Yauyos', 'Vitis'),
  ('Lima', 'Yauyos', 'Viñac'),
  ('Lima', 'Yauyos', 'Yauyos'),
  ('Loreto', 'Alto Amazonas', 'Balsapuerto'),
  ('Loreto', 'Alto Amazonas', 'Jeberos'),
  ('Loreto', 'Alto Amazonas', 'Lagunas'),
  ('Loreto', 'Alto Amazonas', 'Santa Cruz'),
  ('Loreto', 'Alto Amazonas', 'Teniente Cesar Lopez Rojas'),
  ('Loreto', 'Alto Amazonas', 'Yurimaguas'),
  ('Loreto', 'Datem del Marañon', 'Andoas'),
  ('Loreto', 'Datem del Marañon', 'Barranca'),
  ('Loreto', 'Datem del Marañon', 'Cahuapanas'),
  ('Loreto', 'Datem del Marañon', 'Manseriche'),
  ('Loreto', 'Datem del Marañon', 'Morona'),
  ('Loreto', 'Datem del Marañon', 'Pastaza'),
  ('Loreto', 'Loreto', 'Nauta'),
  ('Loreto', 'Loreto', 'Parinari'),
  ('Loreto', 'Loreto', 'Tigre'),
  ('Loreto', 'Loreto', 'Trompeteros'),
  ('Loreto', 'Loreto', 'Urarinas'),
  ('Loreto', 'Mariscal Ramon Castilla', 'Pebas'),
  ('Loreto', 'Mariscal Ramon Castilla', 'Ramon Castilla'),
  ('Loreto', 'Mariscal Ramon Castilla', 'San Pablo'),
  ('Loreto', 'Mariscal Ramon Castilla', 'Yavari'),
  ('Loreto', 'Maynas', 'Alto Nanay'),
  ('Loreto', 'Maynas', 'Belen'),
  ('Loreto', 'Maynas', 'Fernando Lores'),
  ('Loreto', 'Maynas', 'Indiana'),
  ('Loreto', 'Maynas', 'Iquitos'),
  ('Loreto', 'Maynas', 'Las Amazonas'),
  ('Loreto', 'Maynas', 'Mazan'),
  ('Loreto', 'Maynas', 'Napo'),
  ('Loreto', 'Maynas', 'Punchana'),
  ('Loreto', 'Maynas', 'Putumayo'),
  ('Loreto', 'Maynas', 'San Juan Bautista'),
  ('Loreto', 'Maynas', 'Teniente Manuel Clavero'),
  ('Loreto', 'Maynas', 'Torres Causana'),
  ('Loreto', 'Putumayo', 'Putumayo'),
  ('Loreto', 'Putumayo', 'Rosa Panduro'),
  ('Loreto', 'Putumayo', 'Teniente Manuel Clavero'),
  ('Loreto', 'Putumayo', 'Yaguas'),
  ('Loreto', 'Requena', 'Alto Tapiche'),
  ('Loreto', 'Requena', 'Capelo'),
  ('Loreto', 'Requena', 'Emilio San Martin'),
  ('Loreto', 'Requena', 'Jenaro Herrera'),
  ('Loreto', 'Requena', 'Maquia'),
  ('Loreto', 'Requena', 'Puinahua'),
  ('Loreto', 'Requena', 'Requena'),
  ('Loreto', 'Requena', 'Saquena'),
  ('Loreto', 'Requena', 'Soplin'),
  ('Loreto', 'Requena', 'Tapiche'),
  ('Loreto', 'Requena', 'Yaquerana'),
  ('Loreto', 'Ucayali', 'Contamana'),
  ('Loreto', 'Ucayali', 'Inahuaya'),
  ('Loreto', 'Ucayali', 'Padre Marquez'),
  ('Loreto', 'Ucayali', 'Pampa Hermosa'),
  ('Loreto', 'Ucayali', 'Sarayacu'),
  ('Loreto', 'Ucayali', 'Vargas Guerra'),
  ('Madre de Dios', 'Manu', 'Fitzcarrald'),
  ('Madre de Dios', 'Manu', 'Huepetuhe'),
  ('Madre de Dios', 'Manu', 'Madre de Dios'),
  ('Madre de Dios', 'Manu', 'Manu'),
  ('Madre de Dios', 'Tahuamanu', 'Iberia'),
  ('Madre de Dios', 'Tahuamanu', 'Iñapari'),
  ('Madre de Dios', 'Tahuamanu', 'Tahuamanu'),
  ('Madre de Dios', 'Tambopata', 'Inambari'),
  ('Madre de Dios', 'Tambopata', 'Laberinto'),
  ('Madre de Dios', 'Tambopata', 'Las Piedras'),
  ('Madre de Dios', 'Tambopata', 'Tambopata'),
  ('Moquegua', 'General Sanchez Cerro', 'Chojata'),
  ('Moquegua', 'General Sanchez Cerro', 'Coalaque'),
  ('Moquegua', 'General Sanchez Cerro', 'Ichuña'),
  ('Moquegua', 'General Sanchez Cerro', 'La Capilla'),
  ('Moquegua', 'General Sanchez Cerro', 'Lloque'),
  ('Moquegua', 'General Sanchez Cerro', 'Matalaque'),
  ('Moquegua', 'General Sanchez Cerro', 'Omate'),
  ('Moquegua', 'General Sanchez Cerro', 'Puquina'),
  ('Moquegua', 'General Sanchez Cerro', 'Quinistaquillas'),
  ('Moquegua', 'General Sanchez Cerro', 'Ubinas'),
  ('Moquegua', 'General Sanchez Cerro', 'Yunga'),
  ('Moquegua', 'Ilo', 'El Algarrobal'),
  ('Moquegua', 'Ilo', 'Ilo'),
  ('Moquegua', 'Ilo', 'Pacocha'),
  ('Moquegua', 'Mariscal Nieto', 'Carumas'),
  ('Moquegua', 'Mariscal Nieto', 'Cuchumbaya'),
  ('Moquegua', 'Mariscal Nieto', 'Moquegua'),
  ('Moquegua', 'Mariscal Nieto', 'Samegua'),
  ('Moquegua', 'Mariscal Nieto', 'San Cristobal'),
  ('Moquegua', 'Mariscal Nieto', 'Torata'),
  ('Pasco', 'Daniel Alcides Carrion', 'Chacayan'),
  ('Pasco', 'Daniel Alcides Carrion', 'Goyllarisquizga'),
  ('Pasco', 'Daniel Alcides Carrion', 'Paucar'),
  ('Pasco', 'Daniel Alcides Carrion', 'San Pedro de Pillao'),
  ('Pasco', 'Daniel Alcides Carrion', 'Santa Ana de Tusi'),
  ('Pasco', 'Daniel Alcides Carrion', 'Tapuc'),
  ('Pasco', 'Daniel Alcides Carrion', 'Vilcabamba'),
  ('Pasco', 'Daniel Alcides Carrion', 'Yanahuanca'),
  ('Pasco', 'Oxapampa', 'Chontabamba'),
  ('Pasco', 'Oxapampa', 'Constitucion'),
  ('Pasco', 'Oxapampa', 'Huancabamba'),
  ('Pasco', 'Oxapampa', 'Oxapampa'),
  ('Pasco', 'Oxapampa', 'Palcazu'),
  ('Pasco', 'Oxapampa', 'Pozuzo'),
  ('Pasco', 'Oxapampa', 'Puerto Bermudez'),
  ('Pasco', 'Oxapampa', 'Villa Rica'),
  ('Pasco', 'Pasco', 'Chaupimarca'),
  ('Pasco', 'Pasco', 'Huachon'),
  ('Pasco', 'Pasco', 'Huariaca'),
  ('Pasco', 'Pasco', 'Huayllay'),
  ('Pasco', 'Pasco', 'Ninacaca'),
  ('Pasco', 'Pasco', 'Pallanchacra'),
  ('Pasco', 'Pasco', 'Paucartambo'),
  ('Pasco', 'Pasco', 'San Francisco de Asis de Yarusyacan'),
  ('Pasco', 'Pasco', 'Simon Bolivar'),
  ('Pasco', 'Pasco', 'Ticlacayan'),
  ('Pasco', 'Pasco', 'Tinyahuarco'),
  ('Pasco', 'Pasco', 'Vicco'),
  ('Pasco', 'Pasco', 'Yanacancha'),
  ('Piura', 'Ayabaca', 'Ayabaca'),
  ('Piura', 'Ayabaca', 'Frias'),
  ('Piura', 'Ayabaca', 'Jilili'),
  ('Piura', 'Ayabaca', 'Lagunas'),
  ('Piura', 'Ayabaca', 'Montero'),
  ('Piura', 'Ayabaca', 'Pacaipampa'),
  ('Piura', 'Ayabaca', 'Paimas'),
  ('Piura', 'Ayabaca', 'Sapillica'),
  ('Piura', 'Ayabaca', 'Sicchez'),
  ('Piura', 'Ayabaca', 'Suyo'),
  ('Piura', 'Huancabamba', 'Canchaque'),
  ('Piura', 'Huancabamba', 'El Carmen de la Frontera'),
  ('Piura', 'Huancabamba', 'Huancabamba'),
  ('Piura', 'Huancabamba', 'Huarmaca'),
  ('Piura', 'Huancabamba', 'Lalaquiz'),
  ('Piura', 'Huancabamba', 'San Miguel de El Faique'),
  ('Piura', 'Huancabamba', 'Sondor'),
  ('Piura', 'Huancabamba', 'Sondorillo'),
  ('Piura', 'Morropon', 'Buenos Aires'),
  ('Piura', 'Morropon', 'Chalaco'),
  ('Piura', 'Morropon', 'Chulucanas'),
  ('Piura', 'Morropon', 'La Matanza'),
  ('Piura', 'Morropon', 'Morropon'),
  ('Piura', 'Morropon', 'Salitral'),
  ('Piura', 'Morropon', 'San Juan de Bigote'),
  ('Piura', 'Morropon', 'Santa Catalina de Mossa'),
  ('Piura', 'Morropon', 'Santo Domingo'),
  ('Piura', 'Morropon', 'Yamango'),
  ('Piura', 'Paita', 'Amotape'),
  ('Piura', 'Paita', 'Arenal'),
  ('Piura', 'Paita', 'Colan'),
  ('Piura', 'Paita', 'La Huaca'),
  ('Piura', 'Paita', 'Paita'),
  ('Piura', 'Paita', 'Tamarindo'),
  ('Piura', 'Paita', 'Vichayal'),
  ('Piura', 'Piura', 'Castilla'),
  ('Piura', 'Piura', 'Catacaos'),
  ('Piura', 'Piura', 'Cura Mori'),
  ('Piura', 'Piura', 'El Tallan'),
  ('Piura', 'Piura', 'La Arena'),
  ('Piura', 'Piura', 'La Union'),
  ('Piura', 'Piura', 'Las Lomas'),
  ('Piura', 'Piura', 'Piura'),
  ('Piura', 'Piura', 'Tambo Grande'),
  ('Piura', 'Piura', 'Veintiseis de Octubre'),
  ('Piura', 'Sechura', 'Bellavista de la Union'),
  ('Piura', 'Sechura', 'Bernal'),
  ('Piura', 'Sechura', 'Cristo Nos Valga'),
  ('Piura', 'Sechura', 'Rinconada Llicuar'),
  ('Piura', 'Sechura', 'Sechura'),
  ('Piura', 'Sechura', 'Vice'),
  ('Piura', 'Sullana', 'Bellavista'),
  ('Piura', 'Sullana', 'Ignacio Escudero'),
  ('Piura', 'Sullana', 'Lancones'),
  ('Piura', 'Sullana', 'Marcavelica'),
  ('Piura', 'Sullana', 'Miguel Checa'),
  ('Piura', 'Sullana', 'Querecotillo'),
  ('Piura', 'Sullana', 'Salitral'),
  ('Piura', 'Sullana', 'Sullana'),
  ('Piura', 'Talara', 'El Alto'),
  ('Piura', 'Talara', 'La Brea'),
  ('Piura', 'Talara', 'Lobitos'),
  ('Piura', 'Talara', 'Los Organos'),
  ('Piura', 'Talara', 'Mancora'),
  ('Piura', 'Talara', 'Pariñas'),
  ('Puno', 'Azangaro', 'Achaya'),
  ('Puno', 'Azangaro', 'Arapa'),
  ('Puno', 'Azangaro', 'Asillo'),
  ('Puno', 'Azangaro', 'Azangaro'),
  ('Puno', 'Azangaro', 'Caminaca'),
  ('Puno', 'Azangaro', 'Chupa'),
  ('Puno', 'Azangaro', 'Jose Domingo Choquehuanca'),
  ('Puno', 'Azangaro', 'Muñani'),
  ('Puno', 'Azangaro', 'Potoni'),
  ('Puno', 'Azangaro', 'Saman'),
  ('Puno', 'Azangaro', 'San Anton'),
  ('Puno', 'Azangaro', 'San Jose'),
  ('Puno', 'Azangaro', 'San Juan de Salinas'),
  ('Puno', 'Azangaro', 'Santiago de Pupuja'),
  ('Puno', 'Azangaro', 'Tirapata'),
  ('Puno', 'Carabaya', 'Ajoyani'),
  ('Puno', 'Carabaya', 'Ayapata'),
  ('Puno', 'Carabaya', 'Coasa'),
  ('Puno', 'Carabaya', 'Corani'),
  ('Puno', 'Carabaya', 'Crucero'),
  ('Puno', 'Carabaya', 'Ituata'),
  ('Puno', 'Carabaya', 'Macusani'),
  ('Puno', 'Carabaya', 'Ollachea'),
  ('Puno', 'Carabaya', 'San Gaban'),
  ('Puno', 'Carabaya', 'Usicayos'),
  ('Puno', 'Chucuito', 'Desaguadero'),
  ('Puno', 'Chucuito', 'Huacullani'),
  ('Puno', 'Chucuito', 'Juli'),
  ('Puno', 'Chucuito', 'Kelluyo'),
  ('Puno', 'Chucuito', 'Pisacoma'),
  ('Puno', 'Chucuito', 'Pomata'),
  ('Puno', 'Chucuito', 'Zepita'),
  ('Puno', 'El Collao', 'Capazo'),
  ('Puno', 'El Collao', 'Conduriri'),
  ('Puno', 'El Collao', 'Ilave'),
  ('Puno', 'El Collao', 'Pilcuyo'),
  ('Puno', 'El Collao', 'Santa Rosa'),
  ('Puno', 'Huancane', 'Cojata'),
  ('Puno', 'Huancane', 'Huancane'),
  ('Puno', 'Huancane', 'Huatasani'),
  ('Puno', 'Huancane', 'Inchupalla'),
  ('Puno', 'Huancane', 'Pusi'),
  ('Puno', 'Huancane', 'Rosaspata'),
  ('Puno', 'Huancane', 'Taraco'),
  ('Puno', 'Huancane', 'Vilque Chico'),
  ('Puno', 'Lampa', 'Cabanilla'),
  ('Puno', 'Lampa', 'Calapuja'),
  ('Puno', 'Lampa', 'Lampa'),
  ('Puno', 'Lampa', 'Nicasio'),
  ('Puno', 'Lampa', 'Ocuviri'),
  ('Puno', 'Lampa', 'Palca'),
  ('Puno', 'Lampa', 'Paratia'),
  ('Puno', 'Lampa', 'Pucara'),
  ('Puno', 'Lampa', 'Santa Lucia'),
  ('Puno', 'Lampa', 'Vilavila'),
  ('Puno', 'Melgar', 'Antauta'),
  ('Puno', 'Melgar', 'Ayaviri'),
  ('Puno', 'Melgar', 'Cupi'),
  ('Puno', 'Melgar', 'Llalli'),
  ('Puno', 'Melgar', 'Macari'),
  ('Puno', 'Melgar', 'Nuñoa'),
  ('Puno', 'Melgar', 'Orurillo'),
  ('Puno', 'Melgar', 'Santa Rosa'),
  ('Puno', 'Melgar', 'Umachiri'),
  ('Puno', 'Moho', 'Conima'),
  ('Puno', 'Moho', 'Huayrapata'),
  ('Puno', 'Moho', 'Moho'),
  ('Puno', 'Moho', 'Tilali'),
  ('Puno', 'Puno', 'Acora'),
  ('Puno', 'Puno', 'Amantani'),
  ('Puno', 'Puno', 'Atuncolla'),
  ('Puno', 'Puno', 'Capachica'),
  ('Puno', 'Puno', 'Chucuito'),
  ('Puno', 'Puno', 'Coata'),
  ('Puno', 'Puno', 'Huata'),
  ('Puno', 'Puno', 'Mañazo'),
  ('Puno', 'Puno', 'Paucarcolla'),
  ('Puno', 'Puno', 'Pichacani'),
  ('Puno', 'Puno', 'Plateria'),
  ('Puno', 'Puno', 'Puno'),
  ('Puno', 'Puno', 'San Antonio'),
  ('Puno', 'Puno', 'Tiquillaca'),
  ('Puno', 'Puno', 'Vilque'),
  ('Puno', 'San Antonio de Putina', 'Ananea'),
  ('Puno', 'San Antonio de Putina', 'Pedro Vilca Apaza'),
  ('Puno', 'San Antonio de Putina', 'Putina'),
  ('Puno', 'San Antonio de Putina', 'Quilcapuncu'),
  ('Puno', 'San Antonio de Putina', 'Sina'),
  ('Puno', 'San Roman', 'Cabana'),
  ('Puno', 'San Roman', 'Cabanillas'),
  ('Puno', 'San Roman', 'Caracoto'),
  ('Puno', 'San Roman', 'Juliaca'),
  ('Puno', 'San Roman', 'San Miguel'),
  ('Puno', 'Sandia', 'Alto Inambari'),
  ('Puno', 'Sandia', 'Cuyocuyo'),
  ('Puno', 'Sandia', 'Limbani'),
  ('Puno', 'Sandia', 'Patambuco'),
  ('Puno', 'Sandia', 'Phara'),
  ('Puno', 'Sandia', 'Quiaca'),
  ('Puno', 'Sandia', 'San Juan del Oro'),
  ('Puno', 'Sandia', 'San Pedro de Putina Punco'),
  ('Puno', 'Sandia', 'Sandia'),
  ('Puno', 'Sandia', 'Yanahuaya'),
  ('Puno', 'Yunguyo', 'Anapia'),
  ('Puno', 'Yunguyo', 'Copani'),
  ('Puno', 'Yunguyo', 'Cuturapi'),
  ('Puno', 'Yunguyo', 'Ollaraya'),
  ('Puno', 'Yunguyo', 'Tinicachi'),
  ('Puno', 'Yunguyo', 'Unicachi'),
  ('Puno', 'Yunguyo', 'Yunguyo'),
  ('San Martín', 'Bellavista', 'Alto Biavo'),
  ('San Martín', 'Bellavista', 'Bajo Biavo'),
  ('San Martín', 'Bellavista', 'Bellavista'),
  ('San Martín', 'Bellavista', 'Huallaga'),
  ('San Martín', 'Bellavista', 'San Pablo'),
  ('San Martín', 'Bellavista', 'San Rafael'),
  ('San Martín', 'El Dorado', 'Agua Blanca'),
  ('San Martín', 'El Dorado', 'San Jose de Sisa'),
  ('San Martín', 'El Dorado', 'San Martín'),
  ('San Martín', 'El Dorado', 'Santa Rosa'),
  ('San Martín', 'El Dorado', 'Shatoja'),
  ('San Martín', 'Huallaga', 'Alto Saposoa'),
  ('San Martín', 'Huallaga', 'El Eslabon'),
  ('San Martín', 'Huallaga', 'Piscoyacu'),
  ('San Martín', 'Huallaga', 'Sacanche'),
  ('San Martín', 'Huallaga', 'Saposoa'),
  ('San Martín', 'Huallaga', 'Tingo de Saposoa'),
  ('San Martín', 'Lamas', 'Alonso de Alvarado'),
  ('San Martín', 'Lamas', 'Barranquita'),
  ('San Martín', 'Lamas', 'Caynarachi'),
  ('San Martín', 'Lamas', 'Cuñumbuqui'),
  ('San Martín', 'Lamas', 'Lamas'),
  ('San Martín', 'Lamas', 'Pinto Recodo'),
  ('San Martín', 'Lamas', 'Rumisapa'),
  ('San Martín', 'Lamas', 'San Roque de Cumbaza'),
  ('San Martín', 'Lamas', 'Shanao'),
  ('San Martín', 'Lamas', 'Tabalosos'),
  ('San Martín', 'Lamas', 'Zapatero'),
  ('San Martín', 'Mariscal Caceres', 'Campanilla'),
  ('San Martín', 'Mariscal Caceres', 'Huicungo'),
  ('San Martín', 'Mariscal Caceres', 'Juanjui'),
  ('San Martín', 'Mariscal Caceres', 'Pachiza'),
  ('San Martín', 'Mariscal Caceres', 'Pajarillo'),
  ('San Martín', 'Moyobamba', 'Calzada'),
  ('San Martín', 'Moyobamba', 'Habana'),
  ('San Martín', 'Moyobamba', 'Jepelacio'),
  ('San Martín', 'Moyobamba', 'Moyobamba'),
  ('San Martín', 'Moyobamba', 'Soritor'),
  ('San Martín', 'Moyobamba', 'Yantalo'),
  ('San Martín', 'Picota', 'Buenos Aires'),
  ('San Martín', 'Picota', 'Caspisapa'),
  ('San Martín', 'Picota', 'Picota'),
  ('San Martín', 'Picota', 'Pilluana'),
  ('San Martín', 'Picota', 'Pucacaca'),
  ('San Martín', 'Picota', 'San Cristobal'),
  ('San Martín', 'Picota', 'San Hilarion'),
  ('San Martín', 'Picota', 'Shamboyacu'),
  ('San Martín', 'Picota', 'Tingo de Ponasa'),
  ('San Martín', 'Picota', 'Tres Unidos'),
  ('San Martín', 'Rioja', 'Awajun'),
  ('San Martín', 'Rioja', 'Elias Soplin Vargas'),
  ('San Martín', 'Rioja', 'Nueva Cajamarca'),
  ('San Martín', 'Rioja', 'Pardo Miguel'),
  ('San Martín', 'Rioja', 'Posic'),
  ('San Martín', 'Rioja', 'Rioja'),
  ('San Martín', 'Rioja', 'San Fernando'),
  ('San Martín', 'Rioja', 'Yorongos'),
  ('San Martín', 'Rioja', 'Yuracyacu'),
  ('San Martín', 'San Martín', 'Alberto Leveau'),
  ('San Martín', 'San Martín', 'Cacatachi'),
  ('San Martín', 'San Martín', 'Chazuta'),
  ('San Martín', 'San Martín', 'Chipurana'),
  ('San Martín', 'San Martín', 'El Porvenir'),
  ('San Martín', 'San Martín', 'Huimbayoc'),
  ('San Martín', 'San Martín', 'Juan Guerra'),
  ('San Martín', 'San Martín', 'La Banda de Shilcayo'),
  ('San Martín', 'San Martín', 'Morales'),
  ('San Martín', 'San Martín', 'Papaplaya'),
  ('San Martín', 'San Martín', 'San Antonio'),
  ('San Martín', 'San Martín', 'Sauce'),
  ('San Martín', 'San Martín', 'Shapaja'),
  ('San Martín', 'San Martín', 'Tarapoto'),
  ('San Martín', 'Tocache', 'Nuevo Progreso'),
  ('San Martín', 'Tocache', 'Polvora'),
  ('San Martín', 'Tocache', 'Santa Lucia'),
  ('San Martín', 'Tocache', 'Shunte'),
  ('San Martín', 'Tocache', 'Tocache'),
  ('San Martín', 'Tocache', 'Uchiza'),
  ('Tacna', 'Candarave', 'Cairani'),
  ('Tacna', 'Candarave', 'Camilaca'),
  ('Tacna', 'Candarave', 'Candarave'),
  ('Tacna', 'Candarave', 'Curibaya'),
  ('Tacna', 'Candarave', 'Huanuara'),
  ('Tacna', 'Candarave', 'Quilahuani'),
  ('Tacna', 'Jorge Basadre', 'Ilabaya'),
  ('Tacna', 'Jorge Basadre', 'Ite'),
  ('Tacna', 'Jorge Basadre', 'Locumba'),
  ('Tacna', 'Tacna', 'Alto de la Alianza'),
  ('Tacna', 'Tacna', 'Calana'),
  ('Tacna', 'Tacna', 'Ciudad Nueva'),
  ('Tacna', 'Tacna', 'Coronel Gregorio Albarracin Lanchipa'),
  ('Tacna', 'Tacna', 'Inclan'),
  ('Tacna', 'Tacna', 'La Yarada los Palos'),
  ('Tacna', 'Tacna', 'Pachia'),
  ('Tacna', 'Tacna', 'Palca'),
  ('Tacna', 'Tacna', 'Pocollay'),
  ('Tacna', 'Tacna', 'Sama'),
  ('Tacna', 'Tacna', 'Tacna'),
  ('Tacna', 'Tarata', 'Estique'),
  ('Tacna', 'Tarata', 'Estique-pampa'),
  ('Tacna', 'Tarata', 'Heroes Albarracin Chucatamani'),
  ('Tacna', 'Tarata', 'Sitajara'),
  ('Tacna', 'Tarata', 'Susapaya'),
  ('Tacna', 'Tarata', 'Tarata'),
  ('Tacna', 'Tarata', 'Tarucachi'),
  ('Tacna', 'Tarata', 'Ticaco'),
  ('Tumbes', 'Contralmirante Villar', 'Canoas de Punta Sal'),
  ('Tumbes', 'Contralmirante Villar', 'Casitas'),
  ('Tumbes', 'Contralmirante Villar', 'Zorritos'),
  ('Tumbes', 'Tumbes', 'Corrales'),
  ('Tumbes', 'Tumbes', 'La Cruz'),
  ('Tumbes', 'Tumbes', 'Pampas de Hospital'),
  ('Tumbes', 'Tumbes', 'San Jacinto'),
  ('Tumbes', 'Tumbes', 'San Juan de la Virgen'),
  ('Tumbes', 'Tumbes', 'Tumbes'),
  ('Tumbes', 'Zarumilla', 'Aguas Verdes'),
  ('Tumbes', 'Zarumilla', 'Matapalo'),
  ('Tumbes', 'Zarumilla', 'Papayal'),
  ('Tumbes', 'Zarumilla', 'Zarumilla'),
  ('Ucayali', 'Atalaya', 'Raymondi'),
  ('Ucayali', 'Atalaya', 'Sepahua'),
  ('Ucayali', 'Atalaya', 'Tahuania'),
  ('Ucayali', 'Atalaya', 'Yurua'),
  ('Ucayali', 'Coronel Portillo', 'Calleria'),
  ('Ucayali', 'Coronel Portillo', 'Campoverde'),
  ('Ucayali', 'Coronel Portillo', 'Iparia'),
  ('Ucayali', 'Coronel Portillo', 'Manantay'),
  ('Ucayali', 'Coronel Portillo', 'Masisea'),
  ('Ucayali', 'Coronel Portillo', 'Nueva Requena'),
  ('Ucayali', 'Coronel Portillo', 'Yarinacocha'),
  ('Ucayali', 'Padre Abad', 'Alexander Von Humboldt'),
  ('Ucayali', 'Padre Abad', 'Boqueron'),
  ('Ucayali', 'Padre Abad', 'Curimana'),
  ('Ucayali', 'Padre Abad', 'Huipoca'),
  ('Ucayali', 'Padre Abad', 'Irazola'),
  ('Ucayali', 'Padre Abad', 'Neshuya'),
  ('Ucayali', 'Padre Abad', 'Padre Abad'),
  ('Ucayali', 'Purus', 'Purus'),
  ('Áncash', 'Aija', 'Aija'),
  ('Áncash', 'Aija', 'Coris'),
  ('Áncash', 'Aija', 'Huacllan'),
  ('Áncash', 'Aija', 'La Merced'),
  ('Áncash', 'Aija', 'Succha'),
  ('Áncash', 'Antonio Raymondi', 'Aczo'),
  ('Áncash', 'Antonio Raymondi', 'Chaccho'),
  ('Áncash', 'Antonio Raymondi', 'Chingas'),
  ('Áncash', 'Antonio Raymondi', 'Llamellin'),
  ('Áncash', 'Antonio Raymondi', 'Mirgas'),
  ('Áncash', 'Antonio Raymondi', 'San Juan de Rontoy'),
  ('Áncash', 'Asuncion', 'Acochaca'),
  ('Áncash', 'Asuncion', 'Chacas'),
  ('Áncash', 'Bolognesi', 'Abelardo Pardo Lezameta'),
  ('Áncash', 'Bolognesi', 'Antonio Raymondi'),
  ('Áncash', 'Bolognesi', 'Aquia'),
  ('Áncash', 'Bolognesi', 'Cajacay'),
  ('Áncash', 'Bolognesi', 'Canis'),
  ('Áncash', 'Bolognesi', 'Chiquian'),
  ('Áncash', 'Bolognesi', 'Colquioc'),
  ('Áncash', 'Bolognesi', 'Huallanca'),
  ('Áncash', 'Bolognesi', 'Huasta'),
  ('Áncash', 'Bolognesi', 'Huayllacayan'),
  ('Áncash', 'Bolognesi', 'La Primavera'),
  ('Áncash', 'Bolognesi', 'Mangas'),
  ('Áncash', 'Bolognesi', 'Pacllon'),
  ('Áncash', 'Bolognesi', 'San Miguel de Corpanqui'),
  ('Áncash', 'Bolognesi', 'Ticllos'),
  ('Áncash', 'Carhuaz', 'Acopampa'),
  ('Áncash', 'Carhuaz', 'Amashca'),
  ('Áncash', 'Carhuaz', 'Anta'),
  ('Áncash', 'Carhuaz', 'Ataquero'),
  ('Áncash', 'Carhuaz', 'Carhuaz'),
  ('Áncash', 'Carhuaz', 'Marcara'),
  ('Áncash', 'Carhuaz', 'Pariahuanca'),
  ('Áncash', 'Carhuaz', 'San Miguel de Aco'),
  ('Áncash', 'Carhuaz', 'Shilla'),
  ('Áncash', 'Carhuaz', 'Tinco'),
  ('Áncash', 'Carhuaz', 'Yungar'),
  ('Áncash', 'Carlos Fermin Fitzcarrald', 'San Luis'),
  ('Áncash', 'Carlos Fermin Fitzcarrald', 'San Nicolas'),
  ('Áncash', 'Carlos Fermin Fitzcarrald', 'Yauya'),
  ('Áncash', 'Casma', 'Buena Vista Alta'),
  ('Áncash', 'Casma', 'Casma'),
  ('Áncash', 'Casma', 'Comandante Noel'),
  ('Áncash', 'Casma', 'Yautan'),
  ('Áncash', 'Corongo', 'Aco'),
  ('Áncash', 'Corongo', 'Bambas'),
  ('Áncash', 'Corongo', 'Corongo'),
  ('Áncash', 'Corongo', 'Cusca'),
  ('Áncash', 'Corongo', 'La Pampa'),
  ('Áncash', 'Corongo', 'Yanac'),
  ('Áncash', 'Corongo', 'Yupan'),
  ('Áncash', 'Huaraz', 'Cochabamba'),
  ('Áncash', 'Huaraz', 'Colcabamba'),
  ('Áncash', 'Huaraz', 'Huanchay'),
  ('Áncash', 'Huaraz', 'Huaraz'),
  ('Áncash', 'Huaraz', 'Independencia'),
  ('Áncash', 'Huaraz', 'Jangas'),
  ('Áncash', 'Huaraz', 'La Libertad'),
  ('Áncash', 'Huaraz', 'Olleros'),
  ('Áncash', 'Huaraz', 'Pampas'),
  ('Áncash', 'Huaraz', 'Pariacoto'),
  ('Áncash', 'Huaraz', 'Pira'),
  ('Áncash', 'Huaraz', 'Tarica'),
  ('Áncash', 'Huari', 'Anra'),
  ('Áncash', 'Huari', 'Cajay'),
  ('Áncash', 'Huari', 'Chavin de Huantar'),
  ('Áncash', 'Huari', 'Huacachi'),
  ('Áncash', 'Huari', 'Huacchis'),
  ('Áncash', 'Huari', 'Huachis'),
  ('Áncash', 'Huari', 'Huantar'),
  ('Áncash', 'Huari', 'Huari'),
  ('Áncash', 'Huari', 'Masin'),
  ('Áncash', 'Huari', 'Paucas'),
  ('Áncash', 'Huari', 'Ponto'),
  ('Áncash', 'Huari', 'Rahuapampa'),
  ('Áncash', 'Huari', 'Rapayan'),
  ('Áncash', 'Huari', 'San Marcos'),
  ('Áncash', 'Huari', 'San Pedro de Chana'),
  ('Áncash', 'Huari', 'Uco'),
  ('Áncash', 'Huarmey', 'Cochapeti'),
  ('Áncash', 'Huarmey', 'Culebras'),
  ('Áncash', 'Huarmey', 'Huarmey'),
  ('Áncash', 'Huarmey', 'Huayan'),
  ('Áncash', 'Huarmey', 'Malvas'),
  ('Áncash', 'Huaylas', 'Caraz'),
  ('Áncash', 'Huaylas', 'Huallanca'),
  ('Áncash', 'Huaylas', 'Huata'),
  ('Áncash', 'Huaylas', 'Huaylas'),
  ('Áncash', 'Huaylas', 'Mato'),
  ('Áncash', 'Huaylas', 'Pamparomas'),
  ('Áncash', 'Huaylas', 'Pueblo Libre'),
  ('Áncash', 'Huaylas', 'Santa Cruz'),
  ('Áncash', 'Huaylas', 'Santo Toribio'),
  ('Áncash', 'Huaylas', 'Yuracmarca'),
  ('Áncash', 'Mariscal Luzuriaga', 'Casca'),
  ('Áncash', 'Mariscal Luzuriaga', 'Eleazar Guzman Barron'),
  ('Áncash', 'Mariscal Luzuriaga', 'Fidel Olivas Escudero'),
  ('Áncash', 'Mariscal Luzuriaga', 'Llama'),
  ('Áncash', 'Mariscal Luzuriaga', 'Llumpa'),
  ('Áncash', 'Mariscal Luzuriaga', 'Lucma'),
  ('Áncash', 'Mariscal Luzuriaga', 'Musga'),
  ('Áncash', 'Mariscal Luzuriaga', 'Piscobamba'),
  ('Áncash', 'Ocros', 'Acas'),
  ('Áncash', 'Ocros', 'Cajamarquilla'),
  ('Áncash', 'Ocros', 'Carhuapampa'),
  ('Áncash', 'Ocros', 'Cochas'),
  ('Áncash', 'Ocros', 'Congas'),
  ('Áncash', 'Ocros', 'Llipa'),
  ('Áncash', 'Ocros', 'Ocros'),
  ('Áncash', 'Ocros', 'San Cristobal de Rajan'),
  ('Áncash', 'Ocros', 'San Pedro'),
  ('Áncash', 'Ocros', 'Santiago de Chilcas'),
  ('Áncash', 'Pallasca', 'Bolognesi'),
  ('Áncash', 'Pallasca', 'Cabana'),
  ('Áncash', 'Pallasca', 'Conchucos'),
  ('Áncash', 'Pallasca', 'Huacaschuque'),
  ('Áncash', 'Pallasca', 'Huandoval'),
  ('Áncash', 'Pallasca', 'Lacabamba'),
  ('Áncash', 'Pallasca', 'Llapo'),
  ('Áncash', 'Pallasca', 'Pallasca'),
  ('Áncash', 'Pallasca', 'Pampas'),
  ('Áncash', 'Pallasca', 'Santa Rosa'),
  ('Áncash', 'Pallasca', 'Tauca'),
  ('Áncash', 'Pomabamba', 'Huayllan'),
  ('Áncash', 'Pomabamba', 'Parobamba'),
  ('Áncash', 'Pomabamba', 'Pomabamba'),
  ('Áncash', 'Pomabamba', 'Quinuabamba'),
  ('Áncash', 'Recuay', 'Catac'),
  ('Áncash', 'Recuay', 'Cotaparaco'),
  ('Áncash', 'Recuay', 'Huayllapampa'),
  ('Áncash', 'Recuay', 'Llacllin'),
  ('Áncash', 'Recuay', 'Marca'),
  ('Áncash', 'Recuay', 'Pampas Chico'),
  ('Áncash', 'Recuay', 'Pararin'),
  ('Áncash', 'Recuay', 'Recuay'),
  ('Áncash', 'Recuay', 'Tapacocha'),
  ('Áncash', 'Recuay', 'Ticapampa'),
  ('Áncash', 'Santa', 'Caceres del Peru'),
  ('Áncash', 'Santa', 'Chimbote'),
  ('Áncash', 'Santa', 'Coishco'),
  ('Áncash', 'Santa', 'Macate'),
  ('Áncash', 'Santa', 'Moro'),
  ('Áncash', 'Santa', 'Nepeña'),
  ('Áncash', 'Santa', 'Nuevo Chimbote'),
  ('Áncash', 'Santa', 'Samanco'),
  ('Áncash', 'Santa', 'Santa'),
  ('Áncash', 'Sihuas', 'Acobamba'),
  ('Áncash', 'Sihuas', 'Alfonso Ugarte'),
  ('Áncash', 'Sihuas', 'Cashapampa'),
  ('Áncash', 'Sihuas', 'Chingalpo'),
  ('Áncash', 'Sihuas', 'Huayllabamba'),
  ('Áncash', 'Sihuas', 'Quiches'),
  ('Áncash', 'Sihuas', 'Ragash'),
  ('Áncash', 'Sihuas', 'San Juan'),
  ('Áncash', 'Sihuas', 'Sicsibamba'),
  ('Áncash', 'Sihuas', 'Sihuas'),
  ('Áncash', 'Yungay', 'Cascapara'),
  ('Áncash', 'Yungay', 'Mancos'),
  ('Áncash', 'Yungay', 'Matacoto'),
  ('Áncash', 'Yungay', 'Quillo'),
  ('Áncash', 'Yungay', 'Ranrahirca'),
  ('Áncash', 'Yungay', 'Shupluy'),
  ('Áncash', 'Yungay', 'Yanama'),
  ('Áncash', 'Yungay', 'Yungay');
